// 最终补充 - 补齐至5500+
import { initDb, saveDb } from './index.js';
import fs from 'fs'; import path from 'path'; import { fileURLToPath } from 'url';
const __dirname=path.dirname(fileURLToPath(import.meta.url));
await initDb(); const db=(await import('./index.js')).getDb();
db.run(fs.readFileSync(path.join(__dirname,'schema.sql'),'utf-8'));
const iW=db.prepare('INSERT OR IGNORE INTO vocabulary (word,phonetic_us,phonetic_uk,part_of_speech,difficulty_level) VALUES (?,?,?,?,?)');
const iM=db.prepare('INSERT INTO word_meanings (word_id,meaning_cn,is_primary) VALUES (?,?,?)');
const iE=db.prepare('INSERT INTO word_examples (word_id,sentence_en,sentence_cn,exam_type,source_section) VALUES (?,?,?,?,?)');

function ad(w:string,p:string,m:string,d:number):boolean{
  try{iW.run([w,'','',p,d]);const r=db.exec(`SELECT id FROM vocabulary WHERE word='${w.replace(/'/g,"''")}'`);
  if(r.length&&r[0].values.length){const wid=r[0].values[0][0]as number;
  const hm=db.exec(`SELECT id FROM word_meanings WHERE word_id=${wid}`);
  if(!hm.length||!hm[0].values.length){
    iM.run([wid,m,1]);let en=`The significance of ${w} cannot be underestimated.`;let cn=`${m}的重要性不可低估。`;
    if(p.startsWith('v')){en=`We must learn to ${w} effectively.`;cn=`我们必须学会有效地${m}。`;}
    if(p.startsWith('adj')){en=`This is a ${w} aspect of modern society.`;cn=`这是现代社会的一个${m}方面。`;}
    iE.run([wid,en,cn,'CET-6','基础例句']);return true;}}}catch(e){}return false;}

const words:[string,string,string,number][]=[
// E补充
['earnest','adj.','认真的',3],['earthenware','n.','陶器',5],['earthly','adj.','世俗的',4],
['earthquake','n.','地震',2],['ease','v./n.','减轻；容易',2],['Easter','n.','复活节',3],
['eavesdrop','v.','偷听',5],['ebb','n./v.','退潮',4],['eccentric','adj.','古怪的',5],
['echelon','n.','梯队',5],['eclectic','adj.','兼收并蓄的',5],['eclipse','n./v.','日食',4],
['ecosystem','n.','生态系统',3],['ecstasy','n.','狂喜',5],['eddy','n./v.','漩涡',5],
['edgewise','adv.','边缘朝前',5],['edible','adj.','可食用的',3],['edifice','n.','大厦',5],
['editorial','adj./n.','编辑的',3],['eerie','adj.','怪异的',5],['efface','v.','抹去',5],
['effectuate','v.','实现',5],['efficacy','n.','功效',5],['effigy','n.','肖像',5],
['effortless','adj.','容易的',3],['egalitarian','adj.','平等主义的',5],['egocentric','adj.','自我中心的',5],
['elaborate','adj./v.','精心制作的',4],['elapse','v.','流逝',4],['elasticity','n.','弹性',4],
['elation','n.','兴高采烈',5],['elbow','v./n.','肘部',2],['electorate','n.','选民',4],
['electrician','n.','电工',3],['electrode','n.','电极',5],['electromagnetic','adj.','电磁的',4],
['elegance','n.','优雅',3],['elegy','n.','挽歌',5],['elemental','adj.','基本的',4],
['elevate','v.','提升',4],['elicit','v.','引出',5],['eligibility','n.','资格',4],
['eliminate','v.','消除',2],['elite','adj./n.','精英',3],['ellipse','n.','椭圆',5],
['eloquence','n.','雄辩',4],['elude','v.','逃避',5],['emaciate','v.','使憔悴',5],
['embankment','n.','堤防',5],['embargo','n./v.','禁运',5],['embark','v.','着手',4],
['embed','v.','嵌入',3],['embellish','v.','装饰',5],['embezzle','v.','挪用',5],
['emblem','n.','徽章',4],['embrace','v.','拥抱；包含',2],['embroider','v.','刺绣',4],
['embryo','n.','胚胎',4],['emerald','n./adj.','翡翠',4],['emission','n.','排放',3],
['empathy','n.','同理心',4],['emperical','adj.','经验主义的',5],['empower','v.','赋能',3],
['emulate','v.','效仿',4],['enact','v.','制定；演出',4],['enamel','n.','珐琅',5],
['encapsulate','v.','概括',5],['enchant','v.','使陶醉',4],['encircle','v.','环绕',4],
['enclave','n.','飞地',5],['encode','v.','编码',4],['encompass','v.','包含',4],
['encroach','v.','侵占',5],['encumber','v.','阻碍',5],['endanger','v.','危及',3],
['endeavor','n./v.','努力',4],['endemic','adj.','地方性的',5],['endorse','v.','赞同',3],
['endurance','n.','耐力',3],['energize','v.','激励',4],['enforce','v.','执行',3],
['enfranchise','v.','给予选举权',5],['engrave','v.','雕刻',5],['engross','v.','使全神贯注',5],
['engulf','v.','吞没',5],['enigma','n.','谜',5],['enlighten','v.','启发',4],
['enlist','v.','招募',4],['enmity','n.','敌意',5],['ennoble','v.','使崇高',5],
['enormity','n.','巨大',5],['enrage','v.','激怒',4],['enrich','v.','丰富',3],
['enshrine','v.','供奉',5],['ensue','v.','随之发生',5],['entail','v.','需要',4],
['entangle','v.','缠住',5],['enterprising','adj.','有事业心的',4],['enthral','v.','迷住',5],
['entice','v.','引诱',5],['entity','n.','实体',3],['entourage','n.','随行人员',5],
['entreat','v.','恳求',5],['entrench','v.','巩固',5],['entrepreneurial','adj.','企业家的',4],
['entrust','v.','委托',4],['enumerate','v.','列举',5],['enunciate','v.','清晰地发音',5],
['envelop','v.','包裹',4],['enviable','adj.','令人羡慕的',4],['envisage','v.','设想',4],
['envoy','n.','使者',4],['enzyme','n.','酶',4],['ephemeral','adj.','短暂的',5],
['epic','n./adj.','史诗的',4],['epidemic','n./adj.','流行病',3],['epilepsy','n.','癫痫',5],
['episode','n.','一集；事件',2],['epoch','n.','纪元',4],['equate','v.','等同',4],
['equator','n.','赤道',4],['equestrian','adj.','马术的',5],['equilibrium','n.','平衡',4],
['equip','v.','装备',2],['equitable','adj.','公平的',4],['equity','n.','公平；股本',4],
['equivocal','adj.','模棱两可的',5],['eradicate','v.','根除',4],['erode','v.','侵蚀',3],
['erotic','adj.','色情的',5],['err','v.','犯错',4],['erratic','adj.','不稳定的',5],
['erupt','v.','爆发',3],['escalate','v.','升级',3],['escapade','n.','越轨行为',5],
['eschew','v.','避开',5],['escort','n./v.','护送',4],['esophagus','n.','食道',5],
['espionage','n.','间谍活动',5],['essayist','n.','散文家',5],['establishment','n.','机构；建立',3],
['estrange','v.','疏远',5],['estuary','n.','河口',5],['etch','v.','蚀刻',5],
['eternity','n.','永恒',4],['ether','n.','以太',5],['ethical','adj.','道德的',3],
['etiquette','n.','礼仪',4],['euphoria','n.','极度愉悦',5],['evacuate','v.','疏散',4],
['evade','v.','逃避',4],['evaluate','v.','评估',2],['evaporate','v.','蒸发',4],
['eve','n.','前夕',3],['eventuality','n.','可能发生的事',5],['evergreen','adj./n.','常绿的',4],
['evict','v.','驱逐',5],['evocative','adj.','唤起记忆的',5],['evoke','v.','唤起',4],
['exacerbate','v.','加剧',5],['exalt','v.','提升',5],['exasperate','v.','激怒',5],
['excavate','v.','挖掘',4],['excel','v.','优于',3],['excerpt','n.','节选',4],
['excise','v./n.','切除；消费税',5],['exclaim','v.','呼喊',3],['exclude','v.','排除',3],
['excrete','v.','排泄',5],['excruciating','adj.','极痛苦的',5],['exempt','v./adj.','免除',4],
['exertion','n.','努力',4],['exhale','v.','呼气',4],['exhilarate','v.','使兴奋',5],
['exhort','v.','敦促',5],['exile','n./v.','流放',3],['exodus','n.','大批离开',5],
['exonerate','v.','免除责任',5],['exorbitant','adj.','过高的',5],['exotic','adj.','异国情调的',3],
['expansive','adj.','广阔的',4],['expedite','v.','加速',5],['expel','v.','驱逐',4],
['expertise','n.','专长',3],['expiatory','adj.','赎罪的',5],['expire','v.','到期',3],
['explicable','adj.','可解释的',5],['explicit','adj.','明确的',4],['exponent','n.','倡导者',5],
['exposition','n.','阐述；博览会',5],['expound','v.','阐述',5],['expressly','adv.','明确地',4],
['expulsion','n.','驱逐',5],['expunge','v.','删除',5],['exquisite','adj.','精致的',4],
['extant','adj.','现存的',5],['extemporize','v.','即兴发挥',5],['exterior','adj./n.','外部',3],
['exterminate','v.','消灭',5],['extol','v.','赞美',5],['extort','v.','勒索',5],
['extract','n./v.','提取',3],['extradite','v.','引渡',5],['extraneous','adj.','无关的',5],
['extrapolate','v.','推断',5],['extraterrestrial','adj.','外星的',4],['extremity','n.','肢体；极端',4],
['extricate','v.','解救',5],['exuberant','adj.','繁茂的',5],['exude','v.','渗出',5],
['exult','v.','欢跃',5],['eyebrow','n.','眉毛',2],['eyelid','n.','眼睑',4],
// F补充
['fable','n.','寓言',3],['facet','n.','方面',4],['facial','adj.','面部的',2],
['facile','adj.','容易的',5],['faction','n.','派系',4],['factual','adj.','事实的',3],
['fad','n.','时尚',4],['fahrenheit','n.','华氏温度',3],['faintly','adv.','微弱地',3],
['fairly','adv.','相当；公平地',2],['fairy','n.','仙女',2],['fallacy','n.','谬误',5],
['fallible','adj.','会犯错的',5],['fallow','adj.','休耕的',5],['falsify','v.','伪造',5],
['falter','v.','蹒跚',5],['familial','adj.','家庭的',4],['famine','n.','饥荒',3],
['fanatic','n.','狂热者',5],['farce','n.','闹剧',5],['farewell','n.','告别',3],
['fascism','n.','法西斯主义',5],['fastidious','adj.','挑剔的',5],['fathom','v./n.','理解；英寻',5],
['fatigue','n./v.','疲劳',3],['faucet','n.','水龙头',4],['faulty','adj.','有缺陷的',3],
['fauna','n.','动物群',5],['favoritism','n.','偏爱',4],['feasibility','n.','可行性',4],
['feat','n.','功绩',3],['federation','n.','联邦',3],['feedback','n.','反馈',2],
['feign','v.','假装',5],['felicity','n.','幸福',5],['feline','adj.','猫科的',5],
['fellowship','n.','团体；奖学金',4],['felony','n.','重罪',5],['femininity','n.','女性气质',4],
['fencing','n.','击剑',3],['fend','v.','抵挡',4],['ferment','n./v.','发酵',5],
['fern','n.','蕨类',4],['ferocity','n.','凶猛',5],['ferret','v./n.','搜索',5],
['fervent','adj.','热情的',5],['festive','adj.','节日的',3],['fetch','v.','取来',2],
['fetish','n.','迷恋',5],['fetus','n.','胎儿',4],['feud','n./v.','长期不和',5],
['feverish','adj.','发烧的',4],['fiasco','n.','惨败',5],['fickle','adj.','易变的',5],
['fictitious','adj.','虚构的',4],['fidelity','n.','忠诚；保真度',4],['fidget','v./n.','坐立不安',4],
['fiend','n.','恶魔',5],['figurative','adj.','比喻的',4],['filament','n.','细丝',5],
['filial','adj.','子女的',4],['fillings','n.','补牙材料',4],['filth','n.','污秽',4],
['fin','n.','鱼鳍',3],['finalize','v.','最终确定',3],['finesse','n.','技巧',5],
['firearm','n.','枪支',4],['fireplace','n.','壁炉',3],['fishery','n.','渔业',4],
['fissure','n.','裂缝',5],['fitness','n.','健康',2],['fitting','adj./n.','适合的',3],
['fixture','n.','固定装置',4],['flair','n.','才能',4],['flake','n.','薄片',4],
['flamboyant','adj.','艳丽的',5],['flammable','adj.','易燃的',4],['flank','n./v.','侧面',4],
['flap','v./n.','拍打',4],['flask','n.','烧瓶',5],['flatten','v.','使变平',3],
['flatter','v.','奉承',4],['flaunt','v.','炫耀',4],['flavoring','n.','调味品',3],
['flawless','adj.','完美的',3],['fledgling','n./adj.','雏鸟',5],['fleeting','adj.','短暂的',4],
['flex','v.','弯曲',3],['flick','v./n.','轻弹',3],['flicker','v./n.','闪烁',4],
['fling','v.','扔',4],['flip','v./adj.','轻抛；轻率的',3],['flirt','v./n.','调情',4],
['flit','v.','轻快地飞',4],['flora','n.','植物群',5],['floral','adj.','花的',3],
['flounder','v./n.','挣扎',5],['flourish','v.','繁荣',4],['flout','v.','蔑视',5],
['flu','n.','流感',2],['fluency','n.','流利',3],['fluffy','adj.','蓬松的',3],
['flurry','n.','一阵',4],['flux','n.','变动',5],['flyer','n.','传单',3],
['foam','n.','泡沫',3],['focal','adj.','焦点的',4],['foe','n.','敌人',4],
['foggy','adj.','有雾的',3],['foil','v./n.','挫败',5],['fold','v./n.','折叠',2],
['foliage','n.','叶子',4],['folklore','n.','民间传说',4],['folly','n.','愚蠢',4],
['fondle','v.','爱抚',5],['foodstuff','n.','食品',4],['foolproof','adj.','不会出错的',4],
['footnote','n.','脚注',4],['forage','v./n.','觅食',5],['forbear','v.','克制',5],
['forcible','adj.','强制的',4],['ford','n./v.','浅滩',5],['fore','adj./adv.','在前部',4],
['forebode','v.','预示',5],['forefront','n.','最前沿',3],['foregoing','adj.','前述的',4],
['foreground','n.','前景',3],['forensic','adj.','法医的',5],['forerunner','n.','先驱',4],
['foreseeable','adj.','可预见的',4],['forestall','v.','预先阻止',5],['foretell','v.','预言',5],
['forfeit','v./n.','丧失',5],['forge','v.','铸造；伪造',3],['forgo','v.','放弃',5],
['formality','n.','正式手续',4],['formidable','adj.','可怕的',4],['formulate','v.','制定',4],
['forsake','v.','抛弃',5],['forte','n.','长处',5],['forthright','adj.','直率的',5],
['fortification','n.','防御工事',5],['fortify','v.','加强',4],['fortitude','n.','坚韧',5],
['fossilize','v.','石化',4],['foul','adj.','犯规的',3],['fountain','n.','喷泉',3],
['foyer','n.','门厅',4],['fracture','n./v.','骨折',4],['fragility','n.','脆弱',4],
['fragmentation','n.','分裂',4],['fragrant','adj.','芳香的',4],['frail','adj.','脆弱的',4],
['franchise','n.','特许经营权',4],['frankly','adv.','坦白地',3],['frantic','adj.','疯狂似的',4],
['fraternal','adj.','兄弟般的',5],['fraudulent','adj.','欺骗性的',4],['fraught','adj.','充满的',5],
['fray','n./v.','打架',5],['freak','n.','怪人',4],['freckle','n.','雀斑',4],
['freelance','adj./n.','自由职业的',3],['frenzy','n.','疯狂',4],['fret','v.','烦恼',5],
['friction','n.','摩擦',3],['fridge','n.','冰箱',2],['fright','n.','惊吓',3],
['frigid','adj.','严寒的',5],['fringe','n.','边缘',4],['frolic','v./n.','嬉戏',5],
['frontier','n.','边境',3],['frost','n.','霜',2],['froth','n.','泡沫',4],
['frugal','adj.','节俭的',4],['fruitful','adj.','富有成果的',3],['fruition','n.','实现',5],
['frustrate','v.','使沮丧',3],['fugitive','n./adj.','逃亡者',5],['fulcrum','n.','支点',5],
['fume','n./v.','烟雾',4],['fumigate','v.','熏蒸',5],['functional','adj.','功能性的',3],
['funnel','n./v.','漏斗',4],['furious','adj.','狂怒的',3],['furnace','n.','熔炉',4],
['furnish','v.','提供',4],['furrow','n.','犁沟',5],['fury','n.','暴怒',3],
];

console.log(`Inserting ${words.length} words...`);
let n=0;db.run('BEGIN');
for(const w of words){if(ad(...w))n++;}
db.run('COMMIT');saveDb();
console.log(`Done. Inserted ${n}. Total:`,db.exec('SELECT COUNT(*) FROM vocabulary')[0].values[0][0]);
