// 继续补充至5500+
import { initDb, saveDb } from './index.js';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
const __dirname = path.dirname(fileURLToPath(import.meta.url));
await initDb();
const db = (await import('./index.js')).getDb();
db.run(fs.readFileSync(path.join(__dirname,'schema.sql'),'utf-8'));

const iW=db.prepare('INSERT OR IGNORE INTO vocabulary (word,phonetic_us,phonetic_uk,part_of_speech,difficulty_level) VALUES (?,?,?,?,?)');
const iM=db.prepare('INSERT INTO word_meanings (word_id,meaning_cn,is_primary) VALUES (?,?,?)');
const iE=db.prepare('INSERT INTO word_examples (word_id,sentence_en,sentence_cn,exam_type,source_section) VALUES (?,?,?,?,?)');

function ad(w:string,p:string,m:string,d:number){
  try{
    iW.run([w,'','',p,d]);
    const r=db.exec(`SELECT id FROM vocabulary WHERE word='${w.replace(/'/g,"''")}'`);
    if(r.length>0&&r[0].values.length>0){
      const wid=r[0].values[0][0] as number;
      const hm=db.exec(`SELECT id FROM word_meanings WHERE word_id=${wid}`);
      if(hm.length===0||hm[0].values.length===0){
        iM.run([wid,m,1]);
        let en=`The concept of ${w} is widely discussed in academic research.`;
        let cn=`${m}的概念在学术研究中被广泛讨论。`;
        if(p.startsWith('v')){en=`They decided to ${w} the proposal.`;cn=`他们决定${m}该提案。`;}
        if(p.startsWith('adj')){en=`The results were quite ${w}.`;cn=`结果相当${m}。`;}
        iE.run([wid,en,cn,'CET-6','基础例句']);
        return true;
      }
    }
  }catch(e){}
  return false;
}

const words:[string,string,string,number][]=[
['cabin','n.','小木屋',2],['cabinet','n.','内阁；橱柜',3],['cafeteria','n.','自助餐厅',3],
['calamity','n.','灾难',5],['calcium','n.','钙',3],['calf','n.','小牛；小腿',4],
['caliber','n.','口径',4],['calligraphy','n.','书法',4],['calorie','n.','卡路里',2],
['cameo','n.','客串',4],['camouflage','n./v.','伪装',4],['canary','n.','金丝雀',4],
['candid','adj.','坦率的',4],['cannibal','n.','食人族',5],['canny','adj.','精明的',5],
['canoe','n.','独木舟',3],['canopy','n.','天篷',4],['canteen','n.','食堂',3],
['canvas','n.','画布',3],['canyon','n.','峡谷',3],['cape','n.','海角；披风',4],
['capillary','n.','毛细血管',5],['capitalize','v.','利用；资本化',4],['capsule','n.','胶囊',3],
['caption','n.','说明文字',3],['captive','adj./n.','被俘的',4],['caravan','n.','大篷车',4],
['carbohydrate','n.','碳水化合物',4],['carcass','n.','尸体',5],['cardiac','adj.','心脏的',5],
['cardinal','adj.','基本的',5],['caress','n./v.','爱抚',4],['caricature','n.','漫画',5],
['carnage','n.','大屠杀',5],['carnival','n.','狂欢节',3],['carnivore','n.','食肉动物',4],
['carpenter','n.','木匠',3],['carriage','n.','马车',3],['cartel','n.','卡特尔',5],
['cartilage','n.','软骨',5],['carton','n.','纸箱',3],['cartoon','n.','卡通',2],
['carve','v.','雕刻',3],['cascade','n./v.','瀑布；倾泻',4],['cashier','n.','收银员',2],
['casino','n.','赌场',3],['casket','n.','棺材',4],['cassette','n.','盒式磁带',4],
['caste','n.','种姓',5],['casualty','n.','伤亡',4],['catalyst','n.','催化剂',4],
['catastrophe','n.','灾难',4],['catchment','n.','集水区',5],['categorize','v.','分类',4],
['cater','v.','满足需求',4],['cathedral','n.','大教堂',4],['catholic','adj.','天主教的',3],
['cauldron','n.','大锅',5],['causal','adj.','因果的',4],['causality','n.','因果关系',4],
['cautionary','adj.','警示的',4],['cavalry','n.','骑兵',5],['cavern','n.','大洞穴',4],
['cavity','n.','洞；蛀牙',4],['cedar','n.','雪松',4],['celebrity','n.','名人',3],
['celestial','adj.','天上的',5],['cellar','n.','地窖',3],['cellular','adj.','细胞的',3],
['cellulose','n.','纤维素',5],['cement','n./v.','水泥；巩固',3],['cemetery','n.','墓地',3],
['censor','n./v.','审查',4],['censorship','n.','审查制度',4],['census','n.','人口普查',3],
['centennial','n.','百年纪念',5],['centigrade','adj.','摄氏的',3],['centimeter','n.','厘米',2],
['ceramic','n./adj.','陶瓷',3],['cereal','n.','谷物',2],['cerebral','adj.','大脑的',5],
['ceremonial','adj.','仪式的',4],['certainty','n.','确定性',3],['certification','n.','认证',3],
['certify','v.','证明',4],['cessation','n.','停止',5],['chafe','v.','擦痛',5],
['chalk','n.','粉笔',3],['chamber','n.','室；议院',3],['champagne','n.','香槟',3],
['chancellor','n.','大臣；校长',4],['chant','n./v.','圣歌；吟唱',4],['chaos','n.','混乱',3],
['chapel','n.','小教堂',4],['charcoal','n.','木炭',4],['charisma','n.','魅力',4],
['charitable','adj.','慈善的',3],['charter','n./v.','宪章；特许',4],['chase','v./n.','追逐',2],
['chasm','n.','鸿沟',5],['chassis','n.','底盘',5],['chauffeur','n.','司机',4],
['checkpoint','n.','检查站',3],['chef','n.','厨师',2],['cherish','v.','珍惜',3],
['chess','n.','国际象棋',2],['chestnut','n.','栗子',4],['chic','adj.','时髦的',4],
['chieftain','n.','首领',5],['chill','n./v./adj.','寒冷；使冷',3],['chimney','n.','烟囱',3],
['chimpanzee','n.','黑猩猩',3],['chip','n./v.','芯片；碎片',2],['chisel','n./v.','凿子',4],
['chloride','n.','氯化物',5],['chlorine','n.','氯',4],['choir','n.','唱诗班',4],
['choke','v.','窒息',3],['cholesterol','n.','胆固醇',3],['chop','v./n.','砍；排骨',2],
['chord','n.','和弦；弦',4],['chore','n.','家务活',3],['chorus','n.','合唱',3],
['christen','v.','命名',5],['chromatic','adj.','色彩的',5],['chromosome','n.','染色体',4],
['chronicle','n./v.','编年史',4],['chronological','adj.','按时间顺序的',4],['chuck','v.','扔',4],
['chuckle','v.','轻声笑',4],['chunk','n.','大块',3],['churn','v./n.','搅动',4],
['cider','n.','苹果酒',4],['cinder','n.','灰烬',5],['circuit','n.','电路；巡回',3],
['circular','adj.','圆形的；循环的',3],['circulate','v.','流通；传播',3],['circumference','n.','圆周',4],
['circumstance','n.','情况；环境',2],['circus','n.','马戏团',3],['cite','v.','引用',2],
['citizenship','n.','公民身份',2],['civic','adj.','公民的',3],['civilian','n.','平民',3],
['civilization','n.','文明',2],['clad','adj.','穿…衣服的',4],['clam','n.','蛤蜊',4],
['clamp','v./n.','夹紧',4],['clan','n.','宗族',4],['clandestine','adj.','秘密的',5],
['clarify','v.','澄清',3],['clarity','n.','清晰',3],['clash','v./n.','冲突',3],
['clasp','v./n.','紧握',4],['classify','v.','分类',3],['clatter','n./v.','咔嗒声',4],
['clause','n.','条款；从句',3],['cleanse','v.','清洁；净化',4],['clearance','n.','清除；许可',4],
['clench','v.','紧握；咬紧',4],['clergy','n.','神职人员',4],['cliché','n.','陈词滥调',4],
['click','v./n.','点击',2],['clientele','n.','客户',4],['cliff','n.','悬崖',3],
['climax','n.','高潮',4],['cling','v.','紧贴；坚持',4],['clinical','adj.','临床的',3],
['clip','n./v.','夹子；剪辑',2],['cloak','n./v.','斗篷；掩盖',4],['clockwise','adj./adv.','顺时针',3],
['clone','n./v.','克隆',3],['closet','n.','壁橱',3],['closure','n.','关闭；了结',3],
['clot','n./v.','凝块',5],['clown','n.','小丑',3],['clue','n.','线索',2],
['clump','n./v.','丛；聚集',4],['clumsy','adj.','笨拙的',3],['cluster','n./v.','集群',3],
['clutch','v./n.','紧抓',4],['coalition','n.','联盟',4],['coarse','adj.','粗糙的',3],
['coastal','adj.','沿海的',2],['coax','v.','哄骗',5],['cocaine','n.','可卡因',4],
['cockpit','n.','驾驶舱',4],['cocktail','n.','鸡尾酒',3],['coconut','n.','椰子',3],
['codify','v.','编纂',5],['coerce','v.','强迫',5],['coexist','v.','共存',4],
['coffin','n.','棺材',4],['cognition','n.','认知',4],['cognitive','adj.','认知的',3],
['coherent','adj.','连贯的',3],['cohesive','adj.','有凝聚力的',4],['coil','n./v.','线圈；盘绕',3],
['coinage','n.','造币；新词',4],['coincide','v.','同时发生；一致',4],['coincidence','n.','巧合',3],
['collaborate','v.','合作',3],['collage','n.','拼贴画',4],['collapse','v./n.','崩溃',3],
['collar','n.','衣领',2],['collateral','n./adj.','抵押品',5],['collective','adj.','集体的',3],
['collide','v.','碰撞',4],['colloquial','adj.','口语的',5],['colon','n.','冒号；结肠',4],
['colony','n.','殖民地',3],['colossal','adj.','巨大的',4],['columnist','n.','专栏作家',4],
['combat','n./v.','战斗',3],['combustion','n.','燃烧',4],['comedian','n.','喜剧演员',3],
['comet','n.','彗星',4],['commemorate','v.','纪念',4],['commence','v.','开始',4],
['commend','v.','表扬',4],['commentary','n.','评论',3],['commercialize','v.','商业化',4],
['commissioner','n.','专员',4],['commodity','n.','商品',3],['commonplace','adj./n.','平凡的',4],
['commonwealth','n.','联邦',4],['communal','adj.','公共的',4],['commute','v.','通勤',3],
['compact','adj./n./v.','紧凑的',3],['comparable','adj.','可比较的',3],['compartment','n.','隔间',4],
['compass','n.','指南针',3],['compassion','n.','同情',4],['compatible','adj.','兼容的',3],
['compel','v.','强迫',3],['compensate','v.','补偿',3],['competence','n.','能力',3],
['compile','v.','编译；汇编',3],['complacent','adj.','自满的',4],['complement','v./n.','补充',3],
['complexity','n.','复杂性',3],['complicate','v.','使复杂化',3],['complication','n.','并发症',4],
['compliment','n./v.','赞美',2],['comply','v.','遵守',3],['composite','adj./n.','复合的',4],
['composure','n.','沉着',4],['compound','n./adj.','化合物；复合的',3],['comprehend','v.','理解',4],
['compromise','n./v.','妥协',2],['compulsory','adj.','强制性的',4],['conceal','v.','隐藏',3],
['concede','v.','承认；让步',4],['conceit','n.','自负',4],['conceive','v.','构思；怀孕',3],
['concentric','adj.','同心的',5],['conception','n.','概念；怀孕',4],['concerted','adj.','协调的',4],
['concession','n.','让步',4],['concise','adj.','简洁的',4],['conclusive','adj.','决定性的',4],
['concoct','v.','编造',5],['concrete','adj./n.','具体的；混凝土',3],['concur','v.','同意',4],
['concussion','n.','脑震荡',5],['condemn','v.','谴责',3],['condensation','n.','浓缩',4],
['condense','v.','浓缩；简缩',4],['condolence','n.','哀悼',4],['condominium','n.','公寓',3],
['conducive','adj.','有利的',4],['conduct','n./v.','行为；进行',2],['cone','n.','圆锥',4],
['confederate','n.','同盟者',5],['confer','v.','授予；商议',4],['confess','v.','坦白',3],
['confide','v.','倾诉',4],['confine','v.','限制',3],['confiscate','v.','没收',5],
['conform','v.','遵守；符合',4],['confound','v.','使困惑',5],['confront','v.','面对',3],
['Confucian','adj.','儒家的',4],['congenial','adj.','意气相投的',5],['congestion','n.','拥堵',4],
['conglomerate','n.','企业集团',5],['congregate','v.','聚集',4],['congruent','adj.','一致的',5],
['conjecture','n./v.','推测',5],['conjunction','n.','连词；结合',4],['conjure','v.','变出',5],
['connate','adj.','天生的',5],['connoisseur','n.','鉴赏家',5],['conquer','v.','征服',3],
['conquest','n.','征服',4],['conscience','n.','良心',3],['conscientious','adj.','认真负责的',4],
['conscious','adj.','有意识的',2],['consecutive','adj.','连续的',4],['consensus','n.','共识',3],
['consent','n./v.','同意',3],['consequent','adj.','随之发生的',4],['conservation','n.','保护',3],
['conservatism','n.','保守主义',4],['conserve','v.','节约；保护',3],['considerable','adj.','相当大的',3],
['considerate','adj.','体贴的',3],['consist','v.','由…组成',2],['consistency','n.','一致性',3],
['console','v./n.','安慰；控制台',3],['consolidate','v.','巩固',4],['conspicuous','adj.','显眼的',4],
['conspiracy','n.','阴谋',4],['constituent','n./adj.','成分；组成的',4],['constitute','v.','构成',3],
['constitution','n.','宪法；构成',3],['constrain','v.','限制；约束',4],['constraint','n.','约束',3],
['constrict','v.','压缩',5],['consul','n.','领事',5],['consult','v.','咨询',2],
['consultation','n.','咨询',3],['consume','v.','消耗',2],['consumerism','n.','消费主义',4],
['contagious','adj.','传染性的',4],['container','n.','容器',2],['contaminate','v.','污染',4],
['contemplate','v.','沉思；考虑',4],['contemporary','adj.','当代的',3],['contempt','n.','蔑视',4],
['contend','v.','竞争；主张',4],['contentious','adj.','有争议的',5],['contest','n./v.','竞赛',3],
['continental','adj.','大陆的',3],['contingent','adj./n.','依情况而定的',5],['continuity','n.','连续性',4],
['contradict','v.','矛盾；反驳',4],['contraception','n.','避孕',4],['contraceptive','n./adj.','避孕药具',4],
['contraction','n.','收缩',4],['contradictory','adj.','矛盾的',4],['contrast','n./v.','对比',2],
['contravene','v.','违反',5],['controversial','adj.','有争议的',3],['controversy','n.','争议',3],
['convene','v.','召集',4],['convenience','n.','便利',2],['convent','n.','女修道院',5],
['converge','v.','汇聚',4],['converse','v./adj.','交谈；相反的',3],['conversion','n.','转换',4],
['convert','v.','转换',2],['convey','v.','传达',3],['convict','v./n.','定罪',4],
['conviction','n.','信念；定罪',4],['convince','v.','说服',2],['convoy','n./v.','护航',5],
['convulsion','n.','抽搐',5],['cooperate','v.','合作',2],['cooperative','adj.','合作的',3],
['coordinate','v./n.','协调；坐标',3],['cope','v.','应对',2],['copyright','n.','版权',2],
['coral','n./adj.','珊瑚',3],['cord','n.','绳索',3],['cordial','adj.','热情友好的',4],
['core','n./adj.','核心',2],['cork','n.','软木',4],['cornea','n.','角膜',5],
['cornerstone','n.','基石',4],['corporate','adj.','公司的',3],['corporation','n.','公司',2],
['corps','n.','军团',4],['corpse','n.','尸体',4],['correlate','v.','关联',4],
['correlation','n.','相关性',4],['correspond','v.','对应；通信',3],['correspondent','n.','通讯记者',4],
['corridor','n.','走廊',3],['corrode','v.','腐蚀',4],['corrupt','adj./v.','腐败的',3],
['cosmetic','n./adj.','化妆品',3],['cosmic','adj.','宇宙的',4],['cosmopolitan','adj.','世界性的',5],
['cosmos','n.','宇宙',4],['costume','n.','服装',3],['cosy','adj.','舒适的',3],
['cottage','n.','小屋',3],['couch','n.','长沙发',3],['council','n.','委员会',2],
['counsel','n./v.','劝告；律师',4],['counselor','n.','顾问',3],['countdown','n.','倒计时',3],
['counteract','v.','对抗',4],['counterfeit','adj./n.','伪造的',5],['counterpart','n.','对应的人/物',4],
['coup','n.','政变',4],['coupon','n.','优惠券',3],['courageous','adj.','勇敢的',3],
['courteous','adj.','有礼貌的',3],['courtesy','n.','礼貌',3],['coverage','n.','覆盖',3],
['covet','v.','觊觎',5],['coward','n.','懦夫',3],['cozy','adj.','舒适的',3],
['crackdown','n.','镇压',4],['cradle','n.','摇篮',3],['craft','n./v.','手艺；精心制作',2],
['cram','v.','填满；死记硬背',4],['cramp','n./v.','抽筋',4],['crane','n.','起重机；鹤',3],
['crater','n.','火山口',4],['crave','v.','渴望',4],['crawl','v.','爬行',2],
['crease','n./v.','皱痕',4],['credential','n.','证书',4],['credibility','n.','可信度',4],
['credible','adj.','可信的',3],['creed','n.','信条',5],['creek','n.','小溪',4],
['creep','v.','爬行；悄悄移动',3],['cremate','v.','火化',5],['crest','n.','顶峰',4],
['crevice','n.','裂缝',5],['cricket','n.','板球；蟋蟀',3],['crimson','adj./n.','深红色',4],
['cripple','v./n.','使残疾；跛子',4],['crisp','adj.','脆的；清新的',3],['criterion','n.','标准',3],
['critique','n.','评论',4],['crook','n.','骗子',4],['crooked','adj.','弯曲的',4],
['crouch','v.','蹲伏',4],['crown','n./v.','皇冠；加冕',2],['crucial','adj.','关键的',2],
['crude','adj.','粗糙的；天然的',3],['cruise','n./v.','巡航',3],['crumb','n.','碎屑',4],
['crumble','v.','崩溃；粉碎',4],['crumple','v.','弄皱',4],['crusade','n./v.','十字军东征',4],
['crush','v./n.','压碎；迷恋',2],['crust','n.','外壳',3],['crutch','n.','拐杖',4],
['crystal','n./adj.','水晶',3],['cub','n.','幼兽',3],['cube','n.','立方体',2],
['cubic','adj.','立方的',3],['cucumber','n.','黄瓜',2],['cue','n.','提示',3],
['cuisine','n.','烹饪',3],['culminate','v.','达到顶点',5],['culprit','n.','罪犯',4],
['cult','n.','邪教；崇拜',4],['cultivate','v.','培养；耕作',3],['cumulative','adj.','累积的',4],
['cunning','adj./n.','狡猾的',4],['curator','n.','馆长',4],['curb','v./n.','抑制',3],
['curdle','v.','凝结',5],['curfew','n.','宵禁',4],['curiosity','n.','好奇心',2],
['curl','n./v.','卷曲',3],['currency','n.','货币',2],['curriculum','n.','课程',3],
['curse','n./v.','诅咒',3],['cursor','n.','光标',3],['curtail','v.','缩减',5],
['cushion','n.','垫子',3],['custodian','n.','保管人',4],['custody','n.','监护',4],
['customary','adj.','习惯的',4],['cutback','n.','削减',4],['cute','adj.','可爱的',1],
['cyberspace','n.','网络空间',3],['cyclist','n.','骑自行车的人',3],['cyclone','n.','气旋',4],
['cylinder','n.','圆柱体',4],['cynical','adj.','愤世嫉俗的',4],
// D continuation
['dairy','n.','乳制品',2],['dam','n.','水坝',3],['damn','v./adj.','该死的',2],
['damp','adj.','潮湿的',2],['dangle','v.','悬挂',4],['dare','v.','敢于',2],
['dart','v./n.','飞奔；飞镖',4],['dashboard','n.','仪表盘',3],['database','n.','数据库',2],
['daunt','v.','使气馁',5],['daybreak','n.','黎明',3],['daze','v./n.','茫然',4],
['dazzle','v.','使眼花缭乱',4],['deadline','n.','截止日期',2],['deadlock','n.','僵局',4],
['deadly','adj.','致命的',3],['deafen','v.','使聋',4],['dealership','n.','经销商',3],
['debris','n.','碎片',4],['debtor','n.','债务人',4],['debut','n./v.','首次亮相',4],
['decade','n.','十年',1],['deceit','n.','欺骗',4],['deceive','v.','欺骗',3],
['decency','n.','体面',4],['deception','n.','欺骗',4],['decibel','n.','分贝',5],
['decimal','adj./n.','小数',3],['decisive','adj.','决定性的',3],['deck','n.','甲板',3],
['decode','v.','解码',4],['decompose','v.','分解',4],['decor','n.','装饰',3],
['decree','n./v.','法令',5],['decrepit','adj.','破旧的',5],['deduct','v.','扣除',4],
['deduction','n.','扣除；推论',4],['default','n./v.','默认；违约',3],['defendant','n.','被告',4],
['defender','n.','防守者',3],['defer','v.','推迟',4],['defiance','n.','违抗',4],
['deficient','adj.','不足的',4],['deflate','v.','放气',4],['deflect','v.','偏转',5],
['defraud','v.','诈骗',5],['defy','v.','违抗',4],['degenerate','v./adj.','退化',5],
['degrade','v.','贬低；降解',4],['dehydration','n.','脱水',4],['deity','n.','神',5],
['delegate','v./n.','委派；代表',4],['deliberate','adj.','故意的',4],['delicacy','n.','美味',4],
['delighted','adj.','高兴的',2],['delinquent','adj./n.','违法的',5],['deliverance','n.','解救',5],
['delta','n.','三角洲',4],['delude','v.','迷惑',5],['deluge','n./v.','洪水',5],
['demanding','adj.','要求高的',3],['demeanor','n.','举止',5],['demobilize','v.','复员',5],
['demography','n.','人口统计学',4],['demolish','v.','拆除',4],['demon','n.','恶魔',3],
['demonstrate','v.','展示',2],['demote','v.','降级',5],['den','n.','兽穴',4],
['denial','n.','否认',3],['denominate','v.','命名',5],['denote','v.','表示',4],
['denounce','v.','谴责',4],['dental','adj.','牙齿的',3],['dentist','n.','牙医',2],
['departure','n.','离开',2],['dependable','adj.','可靠的',3],['depict','v.','描绘',4],
['deplete','v.','耗尽',4],['deplore','v.','谴责',5],['deploy','v.','部署',3],
['deport','v.','驱逐出境',4],['depose','v.','罢免',5],['depreciate','v.','贬值',5],
['depression','n.','萧条；抑郁',3],['deprive','v.','剥夺',4],['deputy','n.','副手',3],
['derail','v.','出轨',4],['derelict','adj.','废弃的',5],['derive','v.','源自',3],
['dermatology','n.','皮肤病学',5],['derogatory','adj.','贬低的',5],['descendant','n.','后代',4],
['descent','n.','下降；血统',4],['designate','v.','指定',4],['desktop','n.','桌面',2],
['desolate','adj.','荒凉的',4],['despatch','v./n.','派遣',5],['desperate','adj.','绝望的',3],
['despise','v.','鄙视',4],['destine','v.','注定',4],['destiny','n.','命运',3],
['destitute','adj.','赤贫的',5],['detach','v.','分离',4],['detain','v.','拘留',4],
['detect','v.','检测',2],['detention','n.','拘留',4],['deter','v.','阻止',4],
['detergent','n.','洗涤剂',3],['detriment','n.','损害',5],['devastate','v.','毁灭',4],
['deviate','v.','偏离',4],['deviation','n.','偏差',4],['devious','adj.','狡猾的',5],
['devour','v.','吞食',4],['dew','n.','露水',4],['diabetes','n.','糖尿病',3],
['diagnosis','n.','诊断',4],['diagram','n.','图表',3],['dial','n./v.','拨号盘',3],
['diameter','n.','直径',3],['dice','n.','骰子',3],['dictator','n.','独裁者',4],
['diesel','n.','柴油',3],['dietary','adj.','饮食的',3],['differentiate','v.','区分',4],
['diffuse','v./adj.','扩散',4],['digestive','adj.','消化的',4],['digit','n.','数字',3],
['dignify','v.','使有尊严',4],['dike','n.','堤坝',5],['dilute','v.','稀释',4],
['dimension','n.','维度；尺寸',3],['diminish','v.','减少',4],['dine','v.','进餐',3],
['dingy','adj.','肮脏的',4],['dinosaur','n.','恐龙',3],['dioxide','n.','二氧化物',4],
['diploma','n.','文凭',2],['diplomat','n.','外交官',3],['dire','adj.','可怕的',4],
['directory','n.','目录',3],['disability','n.','残疾',3],['disable','v.','使丧失能力',3],
['disarm','v.','裁军',4],['disarray','n.','混乱',4],['discard','v.','丢弃',4],
['discern','v.','辨别',5],['disciplinary','adj.','纪律的',4],['disclose','v.','透露',4],
['disco','n.','迪斯科',3],['discontent','n.','不满',4],['discord','n.','不和谐',5],
['discourse','n.','话语',4],['discrepancy','n.','差异',5],['discretion','n.','自行决定权',4],
['discriminate','v.','区分；歧视',3],['disdain','n./v.','蔑视',5],['disfigure','v.','损毁',5],
['disgrace','n./v.','耻辱',4],['disintegrate','v.','瓦解',5],['disinterested','adj.','无私的',5],
['disjointed','adj.','不连贯的',5],['dislike','v./n.','不喜欢',2],['dislodge','v.','赶出',5],
['dismantle','v.','拆除',4],['dismay','n./v.','惊恐',4],['dismissal','n.','解雇',4],
['disobey','v.','不服从',3],['disorderly','adj.','混乱的',4],['disparity','n.','差异',4],
['dispassionate','adj.','冷静的',5],['dispensary','n.','药房',5],['dispense','v.','分配',4],
['displace','v.','取代',4],['disposable','adj.','一次性的',3],['disregard','v./n.','漠视',4],
['disrepute','n.','坏名声',5],['disrespect','n./v.','不尊重',3],['dissect','v.','解剖',5],
['disseminate','v.','传播',5],['dissent','n./v.','异议',5],['dissertation','n.','论文',4],
['dissident','n.','持不同政见者',5],['dissipate','v.','消散',5],['dissociate','v.','分离',5],
['dissolution','n.','解散',5],['dissonance','n.','不和谐',5],['dissuade','v.','劝阻',5],
['distil','v.','蒸馏',5],['distinction','n.','区别；卓越',3],['distinctive','adj.','独特的',3],
['distinguish','v.','区分',2],['distort','v.','扭曲',4],['distract','v.','使分心',3],
['distraught','adj.','心烦意乱的',5],['distress','n./v.','痛苦',3],['distribute','v.','分配',2],
['disturb','v.','打扰',2],['diverge','v.','分歧',4],['diversify','v.','多样化',4],
['diversion','n.','转向；娱乐',4],['dividend','n.','股息',4],['divine','adj.','神圣的',4],
['dock','n./v.','码头',3],['doctorate','n.','博士学位',4],['doctrine','n.','教条',4],
['dodge','v.','躲避',4],['dogged','adj.','顽强的',5],['dogma','n.','教条',5],
['dole','n./v.','救济金',5],['doll','n.','玩偶',2],['dolphin','n.','海豚',3],
['domain','n.','领域',3],['dome','n.','穹顶',4],['dominion','n.','领土',5],
['donor','n.','捐赠者',3],['doom','n./v.','厄运',3],['dormant','adj.','休眠的',4],
['dosage','n.','剂量',4],['dote','v.','溺爱',5],['doubtless','adv.','无疑地',4],
['dough','n.','面团',3],['dove','n.','鸽子',3],['downfall','n.','垮台',4],
['downgrade','v./n.','降级',4],['downpour','n.','倾盆大雨',4],['downturn','n.','低迷',3],
['doze','v.','打瞌睡',4],['drainage','n.','排水',4],['drastic','adj.','激烈的',3],
['drawback','n.','缺点',3],['dreadful','adj.','可怕的',3],['dreary','adj.','沉闷的',4],
['drench','v.','湿透',4],['drift','v./n.','漂流',3],['drill','n./v.','钻头；训练',3],
['drip','v./n.','滴下',3],['drizzle','n./v.','毛毛雨',4],['droop','v.','下垂',4],
['drowsy','adj.','困倦的',4],['dub','v.','配音；称为',3],['dubious','adj.','可疑的',4],
['duke','n.','公爵',4],['duly','adv.','适当地',4],['dumb','adj.','哑的',2],
['dump','v./n.','倾倒',3],['duplicate','v./n.','复制',4],['dusk','n.','黄昏',2],
['dustbin','n.','垃圾桶',3],['dwarf','n./v.','矮人',4],['dweller','n.','居民',4],
['dwindle','v.','减少',4],['dye','n./v.','染料',3],['dynamic','adj.','动态的',2],
['dynasty','n.','王朝',3],
];

console.log(`Inserting ${words.length} words...`);
let n=0;
db.run('BEGIN');
for(const w of words){if(ad(...w))n++;}
db.run('COMMIT');saveDb();
console.log(`Inserted ${n}. Total:`,db.exec('SELECT COUNT(*) FROM vocabulary')[0].values[0][0]);
