// CET-6 词库 U-Z 最终批 & 补充词汇
import { initDb, getDb, saveDb } from './index.js';
import { initDatabase } from './init.js';

await initDatabase();
const db = getDb();
const iW = db.prepare('INSERT OR IGNORE INTO vocabulary (word,phonetic_us,phonetic_uk,part_of_speech,difficulty_level,frequency_rank,root_word,memory_tip) VALUES (?,?,?,?,?,?,?,?)');
const iM = db.prepare('INSERT INTO word_meanings (word_id,meaning_cn,meaning_en,usage_note,is_primary) VALUES (?,?,?,?,?)');

const allWords: [string,string,string,number][] = [
// ===== U =====
['ultimate','adj./n.','最终的；终极',3],
['ultraviolet','adj.','紫外线的',4],
['unanimous','adj.','一致的',4],
['unavoidable','adj.','不可避免的',3],
['unbiased','adj.','公正的',4],
['uncertainty','n.','不确定性',3],
['uncover','v.','揭示；发现',3],
['underestimate','v.','低估',3],
['undergo','v.','经历；承受',3],
['undergraduate','n.','本科生',2],
['underlying','adj.','潜在的；根本的',4],
['undermine','v.','削弱；破坏',4],
['undertake','v.','承担；着手',3],
['undo','v.','撤销；解开',2],
['undoubtedly','adv.','毫无疑问地',3],
['unemployment','n.','失业',2],
['unexpected','adj.','出乎意料的',2],
['unfold','v.','展开；展现',3],
['unfortunately','adv.','不幸地',2],
['unify','v.','统一',4],
['unique','adj.','独特的；唯一的',2],
['unity','n.','团结；统一',3],
['universal','adj.','普遍的；全世界的',3],
['universe','n.','宇宙',2],
['unprecedented','adj.','史无前例的',4],
['upcoming','adj.','即将来临的',3],
['update','v./n.','更新',2],
['upgrade','v./n.','升级',2],
['uphold','v.','维护；支持',4],
['upright','adj./adv.','正直的；直立地',3],
['uproar','n.','骚动',4],
['upset','v./adj.','使不安；心烦的',2],
['upward','adv./adj.','向上；向上的',2],
['urban','adj.','城市的',2],
['urge','v./n.','催促；强烈欲望',3],
['urgent','adj.','紧急的',2],
['usage','n.','用法；使用',3],
['utilize','v.','利用',3],
['utmost','adj./n.','最大的；最大限度',4],
['utter','v./adj.','说；完全的',3],

// ===== V =====
['vacant','adj.','空着的；空闲的',3],
['vacation','n.','假期',2],
['vaccine','n.','疫苗',3],
['vacuum','n.','真空',3],
['vague','adj.','模糊的；含糊的',3],
['vain','adj.','徒劳的；自负的',3],
['valid','adj.','有效的；合理的',3],
['validate','v.','验证；确认',4],
['validity','n.','有效性',4],
['valve','n.','阀门',4],
['vanish','v.','消失',3],
['vanity','n.','虚荣',4],
['variable','adj./n.','可变的；变量',3],
['variation','n.','变化；差异',3],
['variety','n.','多样性；种类',2],
['vary','v.','变化；不同',3],
['vast','adj.','广阔的；巨大的',2],
['vegetation','n.','植被',3],
['vehicle','n.','车辆；媒介',2],
['vein','n.','静脉；脉络',4],
['velocity','n.','速度',4],
['vendor','n.','供应商',3],
['venture','n./v.','风险企业；冒险',3],
['venue','n.','场地；地点',3],
['verbal','adj.','言语的；口头的',4],
['verdict','n.','裁决',4],
['verge','n.','边缘',4],
['verify','v.','核实；验证',3],
['versatile','adj.','多才多艺的',4],
['verse','n.','诗节；韵文',4],
['version','n.','版本',2],
['versus','prep.','对；与…相比',3],
['vertical','adj.','垂直的',3],
['vessel','n.','船只；容器',3],
['veteran','n./adj.','老兵；老练的',3],
['veto','n./v.','否决',4],
['vibrate','v.','振动',3],
['vice','n./adj.','缺点；副的',3],
['vicious','adj.','恶毒的；凶残的',4],
['victim','n.','受害者',2],
['viewpoint','n.','观点',3],
['vigor','n.','活力',4],
['vigorous','adj.','有活力的',4],
['violate','v.','违反；侵犯',3],
['violation','n.','违反；侵犯',3],
['violence','n.','暴力',2],
['violent','adj.','暴力的；猛烈的',2],
['virtual','adj.','虚拟的',2],
['virtue','n.','美德',3],
['virus','n.','病毒',2],
['visa','n.','签证',2],
['visible','adj.','可见的',2],
['vision','n.','视力；远见；愿景',3],
['visual','adj.','视觉的',2],
['visualize','v.','可视化；想象',4],
['vital','adj.','至关重要的',2],
['vitamin','n.','维生素',2],
['vivid','adj.','生动的；鲜明的',3],
['vocal','adj.','声音的；直言不讳的',4],
['vocation','n.','职业；天职',4],
['void','n./adj.','空白；空的',4],
['volatile','adj.','易变的；挥发性的',5],
['volcano','n.','火山',3],
['volume','n.','音量；体积；卷',2],
['voluntary','adj.','自愿的',3],
['volunteer','n./v.','志愿者；自愿做',2],
['vomit','v./n.','呕吐',3],
['voucher','n.','代金券；凭单',4],
['vow','n./v.','誓言；发誓',3],
['voyage','n./v.','航行',3],
['vulgar','adj.','粗俗的',4],
['vulnerable','adj.','脆弱的；易受伤的',4],

// ===== W =====
['wage','n./v.','工资；发动',2],
['wagon','n.','马车；货车',3],
['waist','n.','腰部',2],
['wander','v.','徘徊；漫步',3],
['ward','n.','病房；区',3],
['warehouse','n.','仓库',3],
['warfare','n.','战争',4],
['warrant','n./v.','许可令；保证',4],
['warrior','n.','战士',3],
['waterproof','adj.','防水的',3],
['wax','n./v.','蜡；给…打蜡',3],
['weaken','v.','削弱',3],
['weapon','n.','武器',2],
['weary','adj.','疲倦的',4],
['weave','v.','编织',3],
['web','n.','网；网络',2],
['wedge','n./v.','楔子；楔入',4],
['weed','n./v.','杂草；除草',3],
['weird','adj.','怪异的',2],
['welfare','n.','福利；幸福',3],
['wellbeing','n.','幸福；安康',3],
['whereas','conj.','然而；鉴于',3],
['whereby','adv.','凭借；通过',4],
['whilst','conj.','当…的时候；然而',3],
['whip','n./v.','鞭子；鞭打',3],
['whirl','v./n.','旋转',4],
['whisper','v./n.','低语',2],
['whistle','n./v.','哨子；吹口哨',3],
['wholesale','n./adj.','批发；批发的',4],
['wholly','adv.','完全地',3],
['wicked','adj.','邪恶的；缺德的',3],
['widespread','adj.','广泛的',2],
['willingness','n.','意愿',3],
['windfall','n.','意外之财',4],
['wipe','v.','擦；擦拭',2],
['wit','n.','机智；智慧',3],
['withdraw','v.','撤回；退出',3],
['withhold','v.','扣留；隐瞒',4],
['withstand','v.','承受；抵抗',4],
['witness','n./v.','目击者；目击',2],
['witty','adj.','机智的；诙谐的',4],
['wonder','v./n.','想知道；奇迹',2],
['wool','n.','羊毛',2],
['workaholic','n.','工作狂',3],
['workshop','n.','研讨会；车间',2],
['worldly','adj.','世俗的',4],
['worship','n./v.','崇拜；敬奉',3],
['worthwhile','adj.','值得的',2],
['wrap','v.','包裹；缠绕',2],
['wreck','n./v.','残骸；破坏',3],
['wrench','v./n.','猛拧；扳手',4],
['wretched','adj.','悲惨的；可怜的',4],
['wrinkle','n./v.','皱纹；起皱',3],
['wrist','n.','手腕',2],

// ===== Y =====
['yacht','n.','游艇',3],
['yawn','v./n.','打哈欠',3],
['yearn','v.','渴望',4],
['yell','v./n.','叫喊',2],
['yield','v./n.','产出；屈服',3],
['youngster','n.','年轻人',3],

// ===== Z =====
['zeal','n.','热情',4],
['zone','n.','区域；地带',2],
['zoom','v./n.','缩放；急剧上升',3],

// ===== 补充常见短语词汇 =====
['underground','adj./adv./n.','地下的；地铁',2],
['utensil','n.','器具',4],
['uproarious','adj.','吵闹的',5],
['upside','n.','好的一面；上方',3],
['utopia','n.','乌托邦',5],
['vaccination','n.','疫苗接种',3],
['vapor','n.','水蒸气',3],
['vinegar','n.','醋',3],
['violin','n.','小提琴',2],
['wasp','n.','黄蜂',4],
['watt','n.','瓦特',3],
['weld','v.','焊接',4],
['wharf','n.','码头',4],
['wink','v./n.','眨眼',3],
['wither','v.','枯萎',4],
['wreath','n.','花环',4],
['yank','v./n.','猛拉',4],
['yoga','n.','瑜伽',2],
['yolk','n.','蛋黄',3],
['zebra','n.','斑马',3],
['zinc','n.','锌',4],
['zip','v./n.','拉链；压缩',2],
['zigzag','n./adj./adv.','之字形',4],
];

console.log(`Inserting ${allWords.length} U-Z + 补充 words...`);
let n = 0;
db.run('BEGIN');
for (const [word,pos,meaning,diff] of allWords) {
  try {
    iW.run([word,'','',pos,diff,null,null,null]);
    const lid = db.exec('SELECT last_insert_rowid() as id');
    const wid = lid[0].values[0][0] as number;
    if (wid > 0) { iM.run([wid,meaning,null,null,1]); n++; }
  } catch(e) { /* skip */ }
}
db.run('COMMIT');
saveDb();
console.log(`Inserted ${n} new words.`);
