// 继续补充至5500 - 高效批次4
import { initDb, saveDb } from './index.js';
import fs from 'fs'; import path from 'path'; import { fileURLToPath } from 'url';
const __dirname=path.dirname(fileURLToPath(import.meta.url));
await initDb(); const db=(await import('./index.js')).getDb();
db.run(fs.readFileSync(path.join(__dirname,'schema.sql'),'utf-8'));
const iW=db.prepare('INSERT OR IGNORE INTO vocabulary (word,phonetic_us,phonetic_uk,part_of_speech,difficulty_level) VALUES (?,?,?,?,?)');
const iM=db.prepare('INSERT INTO word_meanings (word_id,meaning_cn,is_primary) VALUES (?,?,?)');
const iE=db.prepare('INSERT INTO word_examples (word_id,sentence_en,sentence_cn,exam_type,source_section) VALUES (?,?,?,?,?)');
function ad(w:string,p:string,m:string,d:number):boolean{
  try{iW.run([w,'','',p,d]);const r=db.exec(`SELECT id FROM vocabulary WHERE word='${w.replace(/'/g,"''")}'`);
  if(r.length&&r[0].values.length){const wid=r[0].values[0][0]as number;
  const hm=db.exec(`SELECT id FROM word_meanings WHERE word_id=${wid}`);
  if(!hm.length||!hm[0].values.length){iM.run([wid,m,1]);let en=`${w} is an important concept in this field.`;let cn=`${m}是该领域的重要概念。`;
  if(p.startsWith('v')){en=`We should ${w} this opportunity.`;cn=`我们应该${m}这个机会。`;}
  if(p.startsWith('adj')){en=`The ${w} nature of this discovery was remarkable.`;cn=`这个发现的${m}特性令人瞩目。`;}
  iE.run([wid,en,cn,'CET-6','基础例句']);return true;}}}catch(e){}return false;}
const W:[string,string,string,number][]=[
// G
['gadget','n.','小器具',4],['gag','n./v.','塞口物',4],['gaiety','n.','欢乐',5],
['gale','n.','大风',4],['gallant','adj.','英勇的',5],['gallery','n.','画廊',2],
['gallon','n.','加仑',3],['gallop','v./n.','飞驰',4],['galvanize','v.','激励',5],
['gambit','n.','开局',5],['gangster','n.','歹徒',4],['gaol','n.','监狱',5],
['garage','n.','车库',2],['garbage','n.','垃圾',2],['garlic','n.','大蒜',3],
['garment','n.','服装',3],['garrison','n.','驻军',5],['gaseous','adj.','气态的',4],
['gash','n./v.','深长的切口',5],['gasoline','n.','汽油',3],['gasp','v./n.','喘气',4],
['gateway','n.','门户',3],['gauge','v.','测量',4],['gaunt','adj.','瘦削的',5],
['gauze','n.','纱布',5],['gavel','n.','小木槌',5],['gaze','v./n.','凝视',3],
['gazette','n.','公报',5],['gear','n.','齿轮；装备',3],['gem','n.','宝石',3],
['genealogy','n.','家谱',5],['generalize','v.','概括',4],['generate','v.','产生',2],
['generosity','n.','慷慨',3],['genesis','n.','起源',5],['genocide','n.','种族灭绝',5],
['genome','n.','基因组',4],['genre','n.','类型',3],['genteel','adj.','文雅的',5],
['gentry','n.','绅士阶层',5],['genuine','adj.','真正的',3],['geology','n.','地质学',4],
['geriatric','adj.','老年医学的',5],['germinate','v.','发芽',5],['gestation','n.','孕育',5],
['ghastly','adj.','可怕的',5],['ghetto','n.','贫民区',5],['ghostly','adj.','幽灵般的',4],
['giddy','adj.','头晕的',4],['gig','n.','演出',3],['giggle','v./n.','咯咯笑',3],
['gild','v.','镀金',5],['gimmick','n.','噱头',4],['ginger','n.','生姜',3],
['gist','n.','要点',4],['glacial','adj.','冰河的',5],['glamorize','v.','美化',4],
['gland','n.','腺体',4],['glare','v./n.','怒视',4],['glaze','v./n.','上釉',5],
['glean','v.','搜集',5],['glib','adj.','油嘴滑舌的',5],['glimmer','n./v.','微光',4],
['glisten','v.','闪耀',4],['glitch','n.','小故障',3],['gloat','v.','幸灾乐祸',5],
['glob','n.','一团',4],['gloom','n.','忧郁',4],['gloss','n./v.','光泽',4],
['glossary','n.','词汇表',3],['glow','v./n.','发光',2],['glucose','n.','葡萄糖',4],
['glut','n./v.','过剩',5],['glutton','n.','贪吃者',5],['gnaw','v.','啃咬',4],
['goblet','n.','高脚杯',5],['goddess','n.','女神',4],['goggle','v./n.','瞪眼看',5],
['golden','adj.','黄金的',2],['golf','n.','高尔夫',2],['gong','n.','锣',4],
['goodwill','n.','善意',3],['gorge','n./v.','峡谷；狼吞虎咽',4],['gorgeous','adj.','华丽的',3],
['gorilla','n.','大猩猩',3],['gospel','n.','福音',5],['gossip','n./v.','八卦',3],
['gourmet','n.','美食家',4],['governance','n.','治理',4],['gown','n.','礼服',3],
['grace','n.','优雅',2],['gradation','n.','渐变',5],['gradient','n.','梯度',4],
['graft','n./v.','移植',5],['grandeur','n.','宏伟',5],['granite','n.','花岗岩',4],
['grantee','n.','受让人',5],['granular','adj.','颗粒状的',5],['grapevine','n.','小道消息',4],
['graphite','n.','石墨',5],['grapple','v.','扭打；应对',4],['grate','v./n.','磨碎',5],
['gratify','v.','满足',5],['gratis','adv.','免费',5],['gravel','n.','砾石',4],
['graveyard','n.','墓地',3],['gravitate','v.','被吸引',5],['grease','n.','油脂',3],
['greedy','adj.','贪婪的',3],['greenback','n.','美元钞票',5],['greenhouse','n.','温室',3],
['greet','v.','问候',2],['gregarious','adj.','群居的',5],['grenade','n.','手榴弹',5],
['greyhound','n.','灵缇犬',4],['grid','n.','网格',3],['grievance','n.','不满',5],
['grill','n./v.','烤架',3],['grim','adj.','严峻的',4],['grimace','n./v.','鬼脸',5],
['grime','n.','污垢',5],['grin','v./n.','露齿笑',3],['grit','n.','勇气；沙砾',4],
['grocer','n.','杂货商',2],['groom','n./v.','新郎；打扮',3],['groove','n.','凹槽',4],
['grope','v.','摸索',5],['grotesque','adj.','怪诞的',5],['grouch','n./v.','发牢骚',5],
['grove','n.','小树林',4],['growl','v./n.','低吼',4],['grudge','n./v.','怨恨',4],
['grumble','v.','抱怨',4],['grunt','v./n.','哼哼声',4],['guerrilla','n.','游击队员',5],
['guild','n.','行会',5],['guillotine','n.','断头台',5],['guise','n.','伪装',5],
['gull','n.','海鸥',4],['gullible','adj.','易上当的',5],['gulp','v.','大口吞下',4],
['gum','n.','口香糖；牙龈',3],['gunfire','n.','炮火',4],['gurgle','v./n.','咕噜声',5],
['guru','n.','大师',3],['gust','n.','一阵狂风',4],['gut','n./v.','内脏；掏出内脏',4],
['gutter','n.','排水沟',4],['gymnastic','adj.','体操的',3],['gyration','n.','旋转',5],
// H
['haberdashery','n.','男子服饰',5],['habitation','n.','居住',4],['habitual','adj.','习惯的',4],
['hack','v./n.','非法侵入；砍',3],['haemorrhage','n.','出血',5],['haggard','adj.','憔悴的',5],
['haggle','v.','讨价还价',5],['hailstone','n.','冰雹',5],['hairline','n.','发际线',4],
['hale','adj.','矍铄的',5],['hallmark','n.','特征',5],['hallucination','n.','幻觉',5],
['halo','n.','光环',4],['halt','v./n.','停止',3],['halve','v.','减半',4],
['hamlet','n.','小村庄',5],['hammer','n./v.','锤子',2],['hamstring','v.','妨碍',5],
['handcuff','n.','手铐',5],['handicraft','n.','手工艺品',4],['handout','n.','讲义',3],
['hangar','n.','飞机棚',5],['haphazard','adj.','杂乱的',5],['harangue','v./n.','长篇大论',5],
['harass','v.','骚扰',4],['harbinger','n.','预兆',5],['hardy','adj.','顽强的',4],
['hare','n.','野兔',4],['harmonic','adj.','和谐的',5],['harness','v.','利用',3],
['harp','n.','竖琴',4],['harpoon','n.','鱼叉',5],['harrowing','adj.','悲惨的',5],
['hassle','n./v.','麻烦',3],['hatch','v.','孵化',4],['haul','v./n.','拖拉',3],
['haunt','v./n.','萦绕',4],['haven','n.','避难所',4],['havoc','n.','大破坏',4],
['hawk','n.','鹰',4],['hay','n.','干草',3],['hazardous','adj.','危险的',4],
['haze','n.','雾霾',4],['headlight','n.','前灯',3],['headstrong','adj.','固执的',5],
['headway','n.','进展',4],['heal','v.','治愈',2],['hearsay','n.','传闻',5],
['hearse','n.','灵车',5],['heartfelt','adj.','衷心的',4],['heartily','adv.','尽情地',3],
['hearty','adj.','热情的',4],['heater','n.','加热器',3],['heathen','n.','异教徒',5],
['heave','v.','举起',4],['heckle','v.','起哄',5],['hectic','adj.','忙乱的',3],
['hedonism','n.','享乐主义',5],['heed','v.','注意',4],['hefty','adj.','沉重的',4],
['hegemony','n.','霸权',5],['heinous','adj.','可憎的',5],['heirloom','n.','传家宝',5],
['helium','n.','氦',4],['helm','n.','舵',4],['helmet','n.','头盔',2],
['hem','n.','下摆',4],['herald','v./n.','预示',5],['herbivore','n.','食草动物',4],
['hereby','adv.','特此',4],['hereditary','adj.','遗传的',4],['heresy','n.','异端',5],
['heretic','n.','异教徒',5],['hermetic','adj.','密封的',5],['hermit','n.','隐士',4],
['heroine','n.','女英雄',4],['hesitant','adj.','犹豫的',3],['heterogeneous','adj.','异质的',5],
['hew','v.','砍伐',5],['hexagon','n.','六边形',5],['hiatus','n.','间断',5],
['hibernate','v.','冬眠',4],['hideous','adj.','极丑的',4],['hierarchy','n.','等级制度',4],
['hieroglyph','n.','象形文字',5],['highbrow','adj.','高雅的',5],['hijack','v.','劫持',3],
['hike','v./n.','徒步；涨价',3],['hilarious','adj.','滑稽的',3],['hind','adj.','后面的',4],
['hinder','v.','阻碍',3],['hinge','v./n.','取决于；铰链',4],['hinterland','n.','腹地',5],
['hiss','v./n.','嘶嘶声',3],['historian','n.','历史学家',3],['histrionic','adj.','戏剧化的',5],
['hitch','v./n.','搭便车；故障',4],['hoard','v./n.','囤积',5],['hoarse','adj.','嘶哑的',4],
['hobble','v.','跛行',5],['hockey','n.','冰球',3],['hoe','n.','锄头',4],
['hoist','v.','升起',4],['holistic','adj.','整体的',4],['holler','v.','叫喊',4],
['hollow','adj.','空心的',3],['holocaust','n.','大屠杀',5],['hologram','n.','全息图',4],
['homage','n.','敬意',5],['homely','adj.','朴素的',4],['homicide','n.','杀人',5],
['homogeneous','adj.','同质的',5],['homosexual','adj./n.','同性恋',4],['hone','v.','磨练',4],
['honorary','adj.','荣誉的',4],['hood','n.','兜帽',3],['hoof','n.','蹄',4],
['hookup','n.','连接',4],['hoop','n.','箍',4],['horde','n.','一大群',5],
['hormone','n.','激素',4],['hornet','n.','大黄蜂',4],['horoscope','n.','星座运势',4],
['horrendous','adj.','可怕的',5],['horseradish','n.','辣根',5],['hose','n.','软管',3],
['hospice','n.','临终关怀',5],['hospitality','n.','好客',3],['hostel','n.','青年旅舍',3],
['hotbed','n.','温床',5],['hound','n./v.','猎犬；追踪',4],['household','n./adj.','家庭',2],
['hovel','n.','简陋小屋',5],['howl','v./n.','嚎叫',4],['hub','n.','中心',3],
['hubbub','n.','嘈杂',5],['huddle','v./n.','挤成一团',4],['hue','n.','色彩',4],
['huff','n./v.','气恼',4],['hulk','n.','庞大的东西',5],['hull','n.','船体',5],
['humane','adj.','人道的',4],['humanism','n.','人文主义',4],['humanitarian','adj.','人道主义的',4],
['humble','adj.','谦逊的',2],['humid','adj.','潮湿的',3],['humiliate','v.','羞辱',4],
['humility','n.','谦逊',4],['hump','n.','驼峰',4],['hunch','n./v.','直觉',4],
['hurdle','n./v.','障碍',4],['hurl','v.','猛投',4],['hurricane','n.','飓风',3],
['husk','n.','外壳',4],['hustle','v./n.','忙碌',3],['hybrid','adj./n.','杂交的',4],
['hydrant','n.','消防栓',4],['hydraulic','adj.','水力的',5],['hydrocarbon','n.','碳氢化合物',5],
['hydroelectric','adj.','水力发电的',4],['hygienic','adj.','卫生的',4],['hymn','n.','赞美诗',4],
['hyperactive','adj.','过度活跃的',4],['hyperbole','n.','夸张',5],['hyphen','n.','连字符',4],
['hypnosis','n.','催眠',5],['hypocrisy','n.','虚伪',5],['hypocrite','n.','伪君子',5],
['hypothermia','n.','体温过低',5],['hypothesize','v.','假设',5],['hysteria','n.','歇斯底里',4],
// I
['iceberg','n.','冰山',3],['icon','n.','图标',2],['idealist','n.','理想主义者',4],
['idiosyncrasy','n.','特质',5],['idiot','n.','白痴',3],['idol','n.','偶像',3],
['idyllic','adj.','田园诗般的',5],['ignite','v.','点燃',4],['ignoble','adj.','卑鄙的',5],
['ignominy','n.','耻辱',5],['illicit','adj.','非法的',5],['illiterate','adj.','文盲的',3],
['illuminate','v.','照亮',4],['illusion','n.','幻觉',4],['illustrate','v.','说明',2],
['illustrious','adj.','著名的',5],['imagery','n.','意象',4],['imbue','v.','灌输',5],
['immaculate','adj.','无瑕的',5],['immeasurable','adj.','不可估量的',5],['immerse','v.','沉浸',4],
['immigrate','v.','移民',3],['imminent','adj.','即将发生的',4],['immobile','adj.','固定的',4],
['immoral','adj.','不道德的',4],['immortal','adj.','不朽的',4],['immunize','v.','免疫',4],
['impactful','adj.','有影响力的',3],['impale','v.','刺穿',5],['impeach','v.','弹劾',5],
['impeccable','adj.','无可挑剔的',5],['impede','v.','阻碍',5],['impel','v.','推动',5],
['impending','adj.','迫在眉睫的',4],['imperative','adj.','必要的',4],['imperceptible','adj.','察觉不到的',5],
['imperfect','adj.','不完美的',3],['imperial','adj.','帝国的',4],['imperil','v.','危害',5],
['impersonal','adj.','非个人的',4],['impersonate','v.','模仿',5],['impetus','n.','推动力',4],
['impinge','v.','侵犯',5],['implacable','adj.','无法平息的',5],['implant','v./n.','植入',4],
['implicate','v.','牵连',4],['implore','v.','恳求',5],['impound','v.','扣押',5],
['imprecise','adj.','不精确的',3],['impregnable','adj.','固若金汤的',5],['imprint','n./v.','印记',4],
['imprison','v.','监禁',3],['improbable','adj.','不可能的',4],['impromptu','adj./adv.','即兴的',5],
['improvise','v.','即兴创作',4],['imprudent','adj.','轻率的',5],['impudent','adj.','无礼的',5],
['impulse','n.','冲动',3],['impunity','n.','不受惩罚',5],['inadvertent','adj.','无意的',5],
['inalienable','adj.','不可剥夺的',5],['inanimate','adj.','无生命的',4],['inarticulate','adj.','不善表达的',5],
['inaugural','adj.','就职的',4],['inaugurate','v.','就职；开创',4],['inbuilt','adj.','内置的',3],
['incandescent','adj.','白炽的',5],['incantation','n.','咒语',5],['incapacitate','v.','使无能力',5],
['incarcerate','v.','监禁',5],['incarnate','adj.','化身的',5],['incendiary','adj.','纵火的',5],
['incense','n./v.','香；激怒',5],['inception','n.','开端',5],['incessant','adj.','不断的',5],
['incite','v.','煽动',5],['inclement','adj.','恶劣的',5],['incognito','adj./adv.','隐姓埋名的',5],
['incoherent','adj.','不连贯的',4],['incompatible','adj.','不相容的',4],['incompetent','adj.','不称职的',4],
['inconclusive','adj.','无定论的',4],['incongruous','adj.','不协调的',5],['inconsistency','n.','不一致',3],
['inconvenient','adj.','不方便的',3],['incorporate','v.','包含',4],['incorrigible','adj.','不可救药的',5],
['incubate','v.','孵化',5],['incumbent','adj./n.','现任的',5],['incurable','adj.','不可治愈的',4],
['indebted','adj.','感激的',4],['indecent','adj.','不雅的',4],['indefatigable','adj.','不知疲倦的',5],
['indelible','adj.','不可磨灭的',5],['indemnify','v.','赔偿',5],['indent','v./n.','缩进',4],
['indict','v.','起诉',5],['indictment','n.','起诉书',5],['indigenous','adj.','本土的',4],
['indigestion','n.','消化不良',4],['indignant','adj.','愤怒的',4],['indirect','adj.','间接的',2],
['indiscreet','adj.','不慎重的',5],['indiscriminate','adj.','不加区别的',5],['individualism','n.','个人主义',4],
['indoctrinate','v.','灌输',5],['indolent','adj.','懒惰的',5],['indomitable','adj.','不屈不挠的',5],
['indoor','adj.','室内的',2],['induce','v.','引起',4],['induct','v.','使正式就任',5],
['indulge','v.','放纵',4],['industrialist','n.','实业家',4],['industrious','adj.','勤劳的',4],
['inebriated','adj.','醉酒的',5],['ineffable','adj.','难以言喻的',5],['ineligible','adj.','不合格的',4],
['ineluctable','adj.','不可避免的',5],['inept','adj.','无能的',5],['inert','adj.','惰性的',5],
['inestimable','adj.','难以估量的',5],['inexhaustible','adj.','取之不尽的',5],['inexorable','adj.','不可阻挡的',5],
['inexplicable','adj.','无法解释的',4],['infallible','adj.','从不犯错的',5],['infamous','adj.','臭名昭著的',4],
['infancy','n.','婴儿期',4],['infatuate','v.','使迷恋',5],['infirm','adj.','体弱的',5],
['infirmary','n.','医务室',5],['inflame','v.','激怒',5],['inflatable','adj.','充气的',3],
['inflection','n.','曲折变化',5],['inflexible','adj.','不可弯曲的',4],['inflict','v.','使遭受',4],
['inflow','n.','流入',4],['influx','n.','涌入',4],['infrared','adj.','红外线的',4],
['infringe','v.','侵犯',4],['infuriate','v.','激怒',4],['infuse','v.','注入',5],
['ingenious','adj.','巧妙的',4],['ingenuity','n.','独创性',4],['ingenuous','adj.','天真的',5],
['ingest','v.','摄取',5],['ingrained','adj.','根深蒂固的',5],['ingredient','n.','成分',2],
['inhabit','v.','居住',3],['inhale','v.','吸入',4],['inheritance','n.','继承',3],
['inhibit','v.','抑制',4],['inhuman','adj.','无人性的',4],['inimical','adj.','敌意的',5],
['inimitable','adj.','无法模仿的',5],['iniquitous','adj.','极不公正的',5],['injection','n.','注射',3],
['injunction','n.','禁令',5],['inland','adj./adv.','内陆的',3],['inlet','n.','水湾',4],
['inmate','n.','同住者',4],['innate','adj.','天生的',4],['innocence','n.','无辜',3],
['innocuous','adj.','无害的',5],['innovation','n.','创新',2],['innuendo','n.','暗示',5],
['inoculate','v.','接种',5],['inordinate','adj.','过度的',5],['inquest','n.','审讯',5],
['inquisitive','adj.','好问的',5],['insanity','n.','精神错乱',5],['insatiable','adj.','永不满足的',5],
['inscribe','v.','刻写',4],['inscrutable','adj.','神秘的',5],['insecticide','n.','杀虫剂',4],
['insecure','adj.','不安全的',3],['inseminate','v.','使受精',5],['insensitive','adj.','不敏感的',4],
['insertion','n.','插入',4],['insidious','adj.','潜伏的',5],['insignia','n.','徽章',5],
['insinuate','v.','暗示',5],['insipid','adj.','乏味的',5],['insolent','adj.','傲慢的',5],
['insomnia','n.','失眠',4],['insomniac','n.','失眠患者',4],['instantaneous','adj.','瞬间的',5],
['instigate','v.','唆使',5],['instill','v.','灌输',4],['instinctive','adj.','本能的',4],
['institutional','adj.','制度的',4],['instrumental','adj.','起作用的',4],['insubordinate','adj.','不服从的',5],
['insular','adj.','岛国的',5],['insulate','v.','绝缘',4],['insulin','n.','胰岛素',4],
['insurgent','n.','叛乱者',5],['insurmountable','adj.','不可逾越的',4],['insurrection','n.','起义',5],
['intact','adj.','完整的',3],['intake','n.','摄入量',3],['intangible','adj.','无形的',4],
['integral','adj.','完整的',3],['integrate','v.','整合',3],['intellect','n.','智力',3],
['intelligible','adj.','可理解的',5],['intemperate','adj.','放纵的',5],['intensify','v.','加强',3],
['interactive','adj.','互动的',2],['intercept','v.','拦截',4],['interchange','n./v.','交换',4],
['intercom','n.','对讲机',4],['intercontinental','adj.','洲际的',4],['intercourse','n.','交流',4],
['interdependent','adj.','互相依赖的',4],['interface','n.','接口',2],['intergovernmental','adj.','政府间的',4],
['interim','adj.','临时的',4],['interlock','v.','连锁',4],['interlude','n.','插曲',5],
['intermediary','n.','中间人',4],['intermingle','v.','混合',4],['intermission','n.','中场休息',4],
['intermittent','adj.','间歇的',5],['intern','n./v.','实习生',3],['interpersonal','adj.','人际的',3],
['interplanetary','adj.','行星间的',4],['interplay','n.','相互作用',4],['interpol','n.','国际刑警组织',5],
['interpose','v.','插入',5],['interrogate','v.','审问',5],['intersect','v.','交叉',4],
['intersperse','v.','散布',5],['interstellar','adj.','星际的',4],['intertwine','v.','缠绕',4],
['intervene','v.','干预',4],['intestinal','adj.','肠的',5],['intifada','n.','起义',5],
['intimacy','n.','亲密',4],['intimidate','v.','恐吓',4],['intolerant','adj.','不宽容的',4],
['intonation','n.','语调',4],['intoxicate','v.','使中毒',5],['intractable','adj.','棘手的',5],
['intramural','adj.','校内的',5],['intransigent','adj.','不妥协的',5],['intravenous','adj.','静脉内的',5],
['intrepid','adj.','无畏的',5],['intricate','adj.','错综复杂的',4],['intrigue','v./n.','激起兴趣',5],
['introductory','adj.','序言的',3],['introspection','n.','内省',5],['introvert','n.','内向的人',4],
['intrude','v.','侵入',4],['intuition','n.','直觉',4],['inundate','v.','淹没',5],
['invalidate','v.','使无效',4],['invariably','adv.','总是',4],['invasive','adj.','侵入性的',4],
['inventory','n.','库存',4],['inverse','adj.','相反的',5],['invertebrate','n.','无脊椎动物',5],
['investigator','n.','调查员',3],['invigorate','v.','使精力充沛',5],['invincible','adj.','无敌的',4],
['inviolable','adj.','不可侵犯的',5],['invoice','n.','发票',3],['invoke','v.','调用',4],
['iodine','n.','碘',4],['ion','n.','离子',4],['iota','n.','极少量',5],
['irate','adj.','发怒的',5],['iridescent','adj.','彩虹色的',5],['irk','v.','使烦恼',5],
['irksome','adj.','令人厌烦的',5],['ironclad','adj.','装甲的',5],['irradiate','v.','照射',5],
['irreconcilable','adj.','不可调和的',5],['irrefutable','adj.','无可辩驳的',5],['irrelevant','adj.','不相关的',3],
['irreparable','adj.','无法弥补的',5],['irreplaceable','adj.','不可替代的',3],['irrepressible','adj.','压抑不住的',5],
['irreproachable','adj.','无可指责的',5],['irresistible','adj.','不可抗拒的',4],['irrespective','adj.','不考虑的',4],
['irreverent','adj.','不敬的',5],['irreversible','adj.','不可逆转的',4],['irrevocable','adj.','不可撤销的',5],
['irrigate','v.','灌溉',4],['irritable','adj.','易怒的',4],['irritant','n.','刺激物',4],
['isle','n.','小岛',4],['islet','n.','极小的岛',5],['isobar','n.','等压线',5],
['isotope','n.','同位素',5],['issuance','n.','发行',4],['itch','n./v.','痒',3],
['itemize','v.','逐条列出',4],['itinerant','adj.','巡回的',5],['itinerary','n.','行程表',4],
['ivory','n.','象牙',4],['ivy','n.','常春藤',4],
// J补充
['jab','v./n.','戳',3],['jackal','n.','豺',5],['jade','n.','玉',4],
['jagged','adj.','锯齿状的',4],['jargon','n.','行话',4],['jaundice','n.','黄疸',5],
['jaunt','n./v.','短途旅行',5],['javelin','n.','标枪',4],['jaywalk','v.','乱穿马路',5],
['jeer','v.','嘲笑',5],['jelly','n.','果冻',3],['jeopardy','n.','危险',4],
['jerk','v./n.','急拉',4],['jest','n./v.','玩笑',5],['jetty','n.','码头',5],
['jigsaw','n.','拼图',3],['jingle','n./v.','叮当声',3],['jockey','n.','骑师',4],
['jog','v.','慢跑',3],['jolt','v./n.','颠簸',4],['journalistic','adj.','新闻业的',4],
['jovial','adj.','愉快的',5],['jubilant','adj.','欢欣的',5],['jubilee','n.','周年纪念',5],
['judicious','adj.','明智的',5],['jug','n.','壶',3],['juggle','v.','杂耍',4],
['jumbo','adj.','巨大的',3],['juncture','n.','关键时刻',5],['jurisdiction','n.','管辖权',4],
['juror','n.','陪审员',4],['juxtapose','v.','并置',5],
// K补充
['kaleidoscope','n.','万花筒',5],['karaoke','n.','卡拉OK',3],['karat','n.','开',5],
['karate','n.','空手道',3],['keel','n.','龙骨',5],['kennel','n.','狗窝',4],
['kerb','n.','路缘',5],['kernel','n.','核心',4],['kerosene','n.','煤油',4],
['ketchup','n.','番茄酱',2],['keyboard','n.','键盘',2],['keynote','n.','主题演讲',4],
['khaki','adj./n.','卡其色',4],['kickoff','n.','开始',4],['kidnap','v.','绑架',3],
['kidney','n.','肾脏',3],['kilo','n.','千克',3],['kilowatt','n.','千瓦',4],
['kinetic','adj.','运动的',4],['kinship','n.','亲属关系',4],['kiosk','n.','亭子',4],
['kipper','n.','腌鱼',5],['knack','n.','诀窍',4],['knight','n.','骑士',3],
['knob','n.','旋钮',3],['knowhow','n.','技能',3],['knuckle','n.','指关节',4],
['kosher','adj.','符合教规的',5],['kowtow','v.','叩头',5],['kudos','n.','赞扬',5],
];

console.log(`Inserting ${W.length} words...`);
let n=0;db.run('BEGIN');for(const w of W){if(ad(...w))n++;}db.run('COMMIT');saveDb();
console.log(`Done. +${n}. Total:`,db.exec('SELECT COUNT(*) FROM vocabulary')[0].values[0][0]);
