// 批量补齐全部词汇的完整知识点
import { initDb, getDb, saveDb } from './index.js';
import fs from 'fs'; import path from 'path'; import { fileURLToPath } from 'url';
const __dirname=path.dirname(fileURLToPath(import.meta.url));
await initDb();
const db=getDb();
db.run(fs.readFileSync(path.join(__dirname,'schema.sql'),'utf-8'));

// 词根数据库 - 常见前缀/词根/后缀
const prefixes:Record<string,string>={ab:'离开',ad:'向',anti:'反对',auto:'自己',bi:'两个',bio:'生命',co:'共同',com:'一起',con:'共同',contra:'反对',de:'向下/去掉',dis:'否定/分开',en:'使',ex:'向外',extra:'超出',fore:'前',il:'不',im:'不/进入',in:'不/进入',inter:'之间',ir:'不',mal:'坏',micro:'微小',mid:'中间',mis:'错误',mono:'单一',multi:'多',non:'不',over:'过度',pre:'前',pro:'向前',re:'再次/回',semi:'半',sub:'下',super:'超',tele:'远',trans:'穿过',tri:'三',un:'不',under:'下',up:'向上',with:'向后'};
const roots:Record<string,string>={act:'行动',aud:'听',bene:'好',ced:'走',cept:'拿',cid:'落',clud:'关闭',cogn:'知道',corp:'身体',cred:'相信',cur:'跑',cycl:'环',dic:'说',don:'给予',duc:'引导',equ:'相等',fact:'做',fer:'携带',fid:'信任',fin:'结束',flex:'弯曲',flu:'流',form:'形状',gen:'产生',grad:'步',graph:'写',gress:'走',ject:'投掷',jud:'判断',lect:'选择',leg:'法律',log:'言语',luc:'光',man:'手',mand:'命令',mem:'记忆',ment:'心智',min:'小',mit:'发送',mod:'方式',mort:'死亡',mov:'移动',nat:'出生',nov:'新',ord:'顺序',part:'部分',path:'感受',ped:'脚',pel:'推动',pend:'悬挂',phon:'声音',plac:'使满意',plic:'折叠',pon:'放置',port:'携带',pos:'放置',press:'压',prim:'第一',psych:'心灵',put:'思考',rupt:'断裂',scend:'爬',scrib:'写',secut:'跟随',sens:'感觉',sequ:'跟随',serv:'服务',sign:'标记',simil:'相似',sist:'站立',sol:'单独',solv:'解开',spec:'看',spir:'呼吸',struct:'建造',sum:'总和',tact:'接触',tain:'保持',tect:'覆盖',tend:'伸展',terr:'土地',test:'证明',therm:'热',tract:'拉',tribut:'给予',urb:'城市',vac:'空',val:'价值',ven:'来',ver:'真实',vers:'转',vid:'看',voc:'声音',vol:'意愿',volv:'卷'};
const suffixes:Record<string,string>={able:'能...的',al:'...的',ance:'...状态',ation:'...动作',cy:'...状态',dom:'...领域',ed:'...的',ence:'...状态',er:'...者',est:'最...',ful:'充满...的',fy:'使...化',hood:'...状态',ible:'能...的',ic:'...的',ical:'...的',ify:'使...化',ing:'...动作',ion:'...动作',ish:'像...的',ism:'...主义',ist:'...者',ity:'...性质',ive:'...的',ize:'使...化',less:'无...的',logy:'...学',ly:'...地',ment:'...结果',ness:'...性质',or:'...者',ous:'...的',ship:'...关系',sion:'...动作',tion:'...动作',ture:'...结果',ty:'...性质',ward:'向...方向',wise:'以...方式'};

// 找出词根成分
function findRootComponents(word:string):string{
  const w=word.toLowerCase();
  const found:string[]=[];
  // Check prefixes
  for(const[p,m]of Object.entries(prefixes)){
    if(w.startsWith(p)&&w.length>p.length+2){found.push(`${p}(${m})`);break;}
  }
  // Check roots
  for(const[r,m]of Object.entries(roots)){
    if(w.includes(r)&&r.length>=3){found.push(`${r}(${m})`);break;}
  }
  // Check suffixes
  for(const[s,m]of Object.entries(suffixes)){
    if(w.endsWith(s)&&w.length>s.length+2){found.push(`-${s}(${m})`);break;}
  }
  return found.length>0?found.join(' + '):'';
}

// 生成记忆技巧
function makeMemoryTip(word:string,meaning:string):string|null{
  const comps=findRootComponents(word);
  if(!comps)return null;
  const firstChar=meaning.charAt(0);
  return `${comps} → ${meaning}`;
}

// 常用近义词/反义词数据库
const synAntDb:Record<string,[string[],string[]]>={
  abandon:[['give up','desert','quit'],['retain','keep','maintain']],
  ability:[['capability','capacity','talent'],['inability','incapacity']],
  able:[['capable','competent','qualified'],['unable','incapable']],
  abnormal:[['unusual','irregular','atypical'],['normal','typical']],
  abolish:[['eliminate','terminate','cancel'],['establish','create']],
  abroad:[['overseas','internationally'],['domestically','locally']],
  absent:[['missing','away','unavailable'],['present','available']],
  absolute:[['total','complete','utter'],['relative','partial']],
  absorb:[['assimilate','soak up','digest'],['release','emit']],
  abstract:[['theoretical','conceptual'],['concrete','tangible']],
  abundant:[['plentiful','ample','copious'],['scarce','rare','limited']],
  abuse:[['misuse','mistreat','exploit'],['respect','honor']],
  academic:[['scholarly','educational'],['practical','vocational']],
  accelerate:[['speed up','quicken','hasten'],['decelerate','slow']],
  accept:[['receive','embrace','agree'],['refuse','reject','decline']],
  access:[['entry','admission','approach'],['exit','blockage']],
  accomplish:[['achieve','complete','fulfill'],['fail','abandon']],
  accurate:[['exact','precise','correct'],['inaccurate','wrong']],
  achieve:[['attain','accomplish','reach'],['fail','lose']],
  acquire:[['obtain','gain','procure'],['lose','forfeit']],
  active:[['energetic','vigorous','dynamic'],['inactive','passive']],
  actual:[['real','true','genuine'],['imaginary','fake']],
  adapt:[['adjust','modify','accommodate'],['resist','reject']],
  adequate:[['sufficient','enough','ample'],['inadequate','insufficient']],
  adjust:[['adapt','modify','alter'],['preserve','maintain']],
  admire:[['respect','appreciate','esteem'],['despise','scorn']],
  admit:[['confess','acknowledge','concede'],['deny','reject']],
  adopt:[['embrace','accept','take up'],['reject','abandon']],
  advance:[['progress','proceed','develop'],['retreat','regress']],
  advantage:[['benefit','gain','edge'],['disadvantage','drawback']],
  aggressive:[['assertive','forceful','hostile'],['passive','gentle']],
  agree:[['concur','consent','approve'],['disagree','object']],
  ancient:[['old','antique','aged'],['modern','new','contemporary']],
  anger:[['rage','fury','wrath'],['calm','patience']],
  announce:[['declare','proclaim','state'],['conceal','hide']],
  annual:[['yearly'],[]],
  anxious:[['worried','nervous','uneasy'],['calm','relaxed']],
  apparent:[['obvious','evident','clear'],['hidden','obscure']],
  appear:[['emerge','surface','arise'],['disappear','vanish']],
  approve:[['endorse','authorize','sanction'],['disapprove','reject']],
  argue:[['debate','dispute','contend'],['agree','concede']],
  artificial:[['synthetic','man-made','fake'],['natural','genuine']],
  assist:[['help','aid','support'],['hinder','obstruct']],
  associate:[['connect','link','relate'],['separate','disconnect']],
  assume:[['presume','suppose','believe'],['doubt','question']],
  attack:[['assault','strike','assail'],['defend','protect']],
  attempt:[['try','endeavor','strive'],['abandon','quit']],
  attract:[['draw','lure','entice'],['repel','deter']],
  avoid:[['evade','dodge','shun'],['seek','pursue','confront']],
  aware:[['conscious','mindful','informed'],['unaware','ignorant']],
  basic:[['fundamental','essential','primary'],['advanced','complex']],
  battle:[['fight','combat','conflict'],['peace','truce']],
  beautiful:[['attractive','gorgeous','lovely'],['ugly','hideous']],
  begin:[['start','commence','initiate'],['end','finish','conclude']],
  believe:[['trust','accept','credit'],['doubt','disbelieve']],
  benefit:[['advantage','gain','profit'],['harm','loss','disadvantage']],
  bold:[['brave','courageous','daring'],['timid','cowardly']],
  brief:[['short','concise','succinct'],['long','lengthy','detailed']],
  bright:[['brilliant','radiant','luminous'],['dark','dim','dull']],
  broad:[['wide','extensive','vast'],['narrow','limited']],
  calm:[['peaceful','tranquil','serene'],['agitated','anxious','turbulent']],
  capable:[['able','competent','skilled'],['incapable','incompetent']],
  capture:[['seize','catch','arrest'],['release','free','liberate']],
  careful:[['cautious','prudent','vigilant'],['careless','reckless']],
  cause:[['reason','motive','origin'],['effect','result','outcome']],
  cease:[['stop','halt','terminate'],['continue','persist','proceed']],
  certain:[['sure','definite','positive'],['uncertain','doubtful']],
  challenge:[['dare','defy','confront'],['accept','yield','surrender']],
  change:[['alter','modify','transform'],['remain','stay','preserve']],
  cheap:[['inexpensive','affordable','budget'],['expensive','costly','dear']],
  chief:[['main','principal','primary'],['secondary','minor','subordinate']],
  choice:[['option','selection','alternative'],['compulsion','necessity']],
  clean:[['pure','tidy','spotless'],['dirty','filthy','polluted']],
  clear:[['obvious','evident','plain'],['unclear','vague','obscure']],
  clever:[['intelligent','smart','bright'],['stupid','foolish','dull']],
  close:[['shut','seal','near'],['open','distant','far']],
  cold:[['chilly','freezing','frigid'],['hot','warm','heated']],
  combine:[['unite','merge','blend'],['separate','divide','split']],
  comfort:[['ease','relief','solace'],['discomfort','pain','distress']],
  common:[['ordinary','usual','frequent'],['rare','uncommon','unusual']],
  compete:[['contend','rival','contest'],['cooperate','collaborate']],
  complete:[['finish','conclude','finalize'],['begin','start','initiate']],
  complex:[['complicated','intricate','sophisticated'],['simple','easy','basic']],
  concern:[['worry','anxiety','care'],['indifference','unconcern']],
  confident:[['assured','certain','self-assured'],['doubtful','uncertain']],
  confirm:[['verify','validate','corroborate'],['disprove','refute','deny']],
  conflict:[['clash','dispute','struggle'],['harmony','peace','agreement']],
  confuse:[['bewilder','perplex','puzzle'],['clarify','enlighten','explain']],
  connect:[['link','join','attach'],['disconnect','separate','detach']],
  conscious:[['aware','mindful','alert'],['unconscious','unaware']],
  consider:[['contemplate','ponder','reflect'],['ignore','disregard']],
  constant:[['steady','continuous','persistent'],['variable','changing','inconstant']],
  construct:[['build','create','erect'],['destroy','demolish','ruin']],
  continue:[['persist','proceed','endure'],['stop','cease','halt']],
  contrast:[['difference','distinction','divergence'],['similarity','resemblance']],
  contribute:[['donate','give','provide'],['withhold','take','receive']],
  control:[['manage','regulate','govern'],['free','release','liberate']],
  convenient:[['suitable','handy','practical'],['inconvenient','awkward']],
  convince:[['persuade','assure','satisfy'],['dissuade','discourage']],
  correct:[['right','accurate','proper'],['wrong','incorrect','erroneous']],
  courage:[['bravery','valor','daring'],['cowardice','fear','timidity']],
  create:[['make','produce','generate'],['destroy','demolish','ruin']],
  critical:[['crucial','vital','essential'],['unimportant','trivial','minor']],
  cruel:[['brutal','ruthless','merciless'],['kind','compassionate','merciful']],
  curious:[['inquisitive','interested','eager'],['indifferent','uninterested']],
  damage:[['harm','injury','destruction'],['repair','fix','mend']],
  danger:[['risk','hazard','peril'],['safety','security','protection']],
  deal:[['agreement','bargain','transaction'],['disagreement','dispute']],
  debate:[['discuss','argue','dispute'],['agree','concede']],
  decide:[['determine','resolve','settle'],['hesitate','waver','vacillate']],
  decline:[['decrease','diminish','refuse'],['increase','rise','accept']],
  decrease:[['reduce','lessen','diminish'],['increase','grow','expand']],
  defeat:[['beat','overcome','conquer'],['lose','surrender','yield']],
  defend:[['protect','guard','shield'],['attack','assault','threaten']],
  definite:[['certain','sure','clear'],['indefinite','vague','uncertain']],
  demand:[['require','request','insist'],['supply','provide','offer']],
  depend:[['rely','trust','count on'],['distrust','doubt']],
  describe:[['depict','portray','explain'],['misrepresent','distort']],
  desire:[['want','wish','longing'],['aversion','disgust','indifference']],
  destroy:[['demolish','ruin','wreck'],['build','create','construct']],
  develop:[['grow','evolve','progress'],['stagnate','decline','regress']],
  differ:[['vary','disagree','contrast'],['agree','concur','resemble']],
  difficult:[['hard','challenging','tough'],['easy','simple','effortless']],
  discover:[['find','uncover','detect'],['hide','conceal','lose']],
  disease:[['illness','sickness','ailment'],['health','wellness','fitness']],
  display:[['show','exhibit','present'],['hide','conceal','cover']],
  distant:[['far','remote','faraway'],['close','near','adjacent']],
  distinct:[['different','separate','clear'],['similar','same','indistinct']],
  divide:[['split','separate','part'],['unite','combine','join']],
  domestic:[['household','home','internal'],['foreign','international','wild']],
  doubt:[['uncertainty','skepticism','suspicion'],['certainty','confidence','trust']],
  dramatic:[['theatrical','striking','spectacular'],['ordinary','mundane','unremarkable']],
  eager:[['keen','enthusiastic','anxious'],['reluctant','unwilling','indifferent']],
  economic:[['financial','monetary','commercial'],['uneconomic','unprofitable']],
  educate:[['teach','instruct','train'],['mislead','misinform']],
  effective:[['efficient','successful','productive'],['ineffective','useless']],
  efficient:[['effective','productive','competent'],['inefficient','wasteful']],
  effort:[['attempt','endeavor','struggle'],['ease','effortlessness']],
  eliminate:[['remove','eradicate','abolish'],['create','establish','introduce']],
  emerge:[['appear','surface','arise'],['disappear','vanish','submerge']],
  emotion:[['feeling','sentiment','passion'],['indifference','apathy']],
  emphasize:[['stress','highlight','underline'],['downplay','minimize','ignore']],
  employ:[['hire','engage','recruit'],['dismiss','fire','sack']],
  enable:[['allow','permit','empower'],['prevent','disable','hinder']],
  encourage:[['support','motivate','inspire'],['discourage','dissuade','deter']],
  energy:[['power','vigor','vitality'],['lethargy','fatigue','weakness']],
  engage:[['involve','participate','occupy'],['disengage','withdraw','release']],
  enhance:[['improve','boost','strengthen'],['diminish','reduce','weaken']],
  enormous:[['huge','immense','vast'],['tiny','small','minute']],
  ensure:[['guarantee','secure','assure'],['risk','endanger','jeopardize']],
  entire:[['whole','complete','total'],['partial','incomplete']],
  environment:[['surroundings','habitat','setting'],['void','emptiness']],
  equal:[['same','equivalent','identical'],['unequal','different','distinct']],
  error:[['mistake','fault','blunder'],['correctness','accuracy','precision']],
  essential:[['necessary','vital','crucial'],['unnecessary','optional','inessential']],
  establish:[['found','create','set up'],['destroy','abolish','dismantle']],
  evaluate:[['assess','judge','appraise'],['ignore','neglect','overlook']],
  evidence:[['proof','testimony','indication'],['disproof','refutation']],
  exact:[['precise','accurate','correct'],['approximate','rough','vague']],
  examine:[['inspect','scrutinize','investigate'],['overlook','ignore','neglect']],
  excellent:[['outstanding','superb','splendid'],['poor','terrible','inferior']],
  exchange:[['trade','swap','barter'],['keep','retain','hold']],
  exclude:[['omit','bar','prohibit'],['include','admit','allow']],
  exercise:[['workout','training','practice'],['rest','inactivity','idleness']],
  exist:[['be','live','survive'],['die','perish','vanish']],
  expand:[['enlarge','extend','broaden'],['shrink','contract','reduce']],
  expect:[['anticipate','await','predict'],['doubt','question']],
  expensive:[['costly','pricey','dear'],['cheap','inexpensive','affordable']],
  experience:[['knowledge','skill','expertise'],['inexperience','ignorance']],
  explain:[['clarify','elucidate','interpret'],['confuse','obscure','mislead']],
  explore:[['investigate','search','examine'],['ignore','overlook','neglect']],
  express:[['convey','communicate','state'],['suppress','withhold','conceal']],
  extend:[['lengthen','prolong','stretch'],['shorten','contract','reduce']],
  extreme:[['utmost','maximum','radical'],['moderate','mild','temperate']],
  fail:[['lose','flop','miscarry'],['succeed','pass','achieve']],
  fair:[['just','impartial','unbiased'],['unfair','biased','unjust']],
  faith:[['belief','trust','confidence'],['doubt','skepticism','unbelief']],
  false:[['untrue','incorrect','wrong'],['true','correct','accurate']],
  familiar:[['known','recognizable','common'],['unfamiliar','strange','unknown']],
  famous:[['renowned','celebrated','notable'],['unknown','obscure','anonymous']],
  fashion:[['style','trend','vogue'],['outdated','unfashionable']],
  favor:[['prefer','support','approve'],['oppose','dislike','reject']],
  fear:[['terror','dread','fright'],['courage','bravery','confidence']],
  final:[['last','ultimate','conclusive'],['first','initial','preliminary']],
  finance:[['funding','money','capital'],['poverty','debt','bankruptcy']],
  firm:[['solid','steady','stable'],['weak','unstable','flexible']],
  flexible:[['adaptable','elastic','pliable'],['rigid','stiff','inflexible']],
  focus:[['concentrate','center','target'],['distract','scatter','disperse']],
  force:[['power','strength','might'],['weakness','feebleness','fragility']],
  foreign:[['alien','external','overseas'],['domestic','native','local']],
  formal:[['official','ceremonial','proper'],['informal','casual','relaxed']],
  former:[['previous','prior','ex-'],['latter','subsequent','following']],
  fortune:[['wealth','luck','destiny'],['misfortune','poverty','bad luck']],
  free:[['liberated','unrestricted','independent'],['restricted','bound','enslaved']],
  frequent:[['regular','common','recurrent'],['rare','infrequent','occasional']],
  friendly:[['amiable','cordial','sociable'],['hostile','unfriendly','cold']],
  gain:[['acquire','obtain','earn'],['lose','forfeit','surrender']],
  general:[['broad','universal','common'],['specific','particular','detailed']],
  gentle:[['mild','soft','tender'],['rough','harsh','violent']],
  genuine:[['real','authentic','true'],['fake','false','counterfeit']],
  global:[['worldwide','universal','international'],['local','regional','national']],
  govern:[['rule','control','manage'],['follow','obey','submit']],
  gradual:[['slow','steady','progressive'],['sudden','abrupt','rapid']],
  grateful:[['thankful','appreciative','obliged'],['ungrateful','thankless']],
  guarantee:[['assure','promise','warrant'],['risk','uncertainty','doubt']],
  guilty:[['culpable','blameworthy','at fault'],['innocent','blameless']],
  happy:[['joyful','cheerful','delighted'],['sad','unhappy','miserable']],
  hard:[['difficult','tough','challenging'],['easy','simple','soft']],
  harmful:[['damaging','destructive','injurious'],['harmless','beneficial','safe']],
  healthy:[['fit','well','robust'],['unhealthy','sick','ill']],
  heavy:[['weighty','massive','burdensome'],['light','weightless','easy']],
  hide:[['conceal','cover','mask'],['reveal','expose','show']],
  honest:[['truthful','sincere','frank'],['dishonest','deceitful','false']],
  huge:[['enormous','immense','gigantic'],['tiny','small','minute']],
  human:[['person','mortal','individual'],['inhuman','divine','animal']],
  ideal:[['perfect','optimal','exemplary'],['flawed','imperfect','realistic']],
  identify:[['recognize','distinguish','diagnose'],['confuse','mistake','misidentify']],
  ignore:[['disregard','overlook','neglect'],['notice','heed','acknowledge']],
  illegal:[['unlawful','illicit','criminal'],['legal','lawful','legitimate']],
  imagine:[['visualize','conceive','fantasize'],['know','realize','comprehend']],
  immediate:[['instant','prompt','urgent'],['delayed','deferred','postponed']],
  impact:[['effect','influence','consequence'],['cause','origin','source']],
  important:[['significant','crucial','vital'],['unimportant','trivial','minor']],
  impose:[['dictate','enforce','inflict'],['remove','lift','withdraw']],
  improve:[['enhance','better','upgrade'],['worsen','deteriorate','decline']],
  include:[['contain','comprise','incorporate'],['exclude','omit','remove']],
  increase:[['rise','grow','expand'],['decrease','reduce','diminish']],
  indicate:[['show','suggest','signal'],['conceal','hide','obscure']],
  individual:[['personal','single','unique'],['collective','group','shared']],
  industry:[['business','manufacturing','trade'],['agriculture','farming']],
  influence:[['affect','impact','sway'],['powerlessness','impotence']],
  inform:[['notify','tell','advise'],['withhold','conceal','hide']],
  innocent:[['guiltless','blameless','naive'],['guilty','culpable','corrupt']],
  insist:[['demand','persist','maintain'],['yield','concede','relent']],
  intelligent:[['smart','clever','bright'],['stupid','dull','ignorant']],
  intense:[['extreme','fierce','powerful'],['mild','moderate','gentle']],
  interest:[['curiosity','attention','concern'],['boredom','indifference','apathy']],
  internal:[['inner','interior','inside'],['external','outer','outside']],
  involve:[['include','entail','require'],['exclude','omit','leave out']],
  issue:[['problem','matter','topic'],['solution','answer','resolution']],
  join:[['connect','unite','link'],['separate','divide','disconnect']],
  judge:[['evaluate','assess','decide'],['misjudge','misinterpret','err']],
  justice:[['fairness','equity','impartiality'],['injustice','unfairness','bias']],
  justify:[['defend','explain','rationalize'],['condemn','accuse','blame']],
  keen:[['eager','enthusiastic','sharp'],['dull','indifferent','blunt']],
  kind:[['benevolent','compassionate','gentle'],['cruel','mean','unkind']],
  knowledge:[['understanding','wisdom','expertise'],['ignorance','unawareness']],
  lack:[['shortage','deficiency','scarcity'],['abundance','surplus','plenty']],
  large:[['big','huge','massive'],['small','tiny','little']],
  lead:[['guide','direct','conduct'],['follow','trail','pursue']],
  legal:[['lawful','legitimate','valid'],['illegal','unlawful','illicit']],
  level:[['degree','standard','rank'],['uneven','irregular','variable']],
  liberal:[['progressive','tolerant','generous'],['conservative','strict','stingy']],
  likely:[['probable','expected','possible'],['unlikely','improbable']],
  limit:[['restrict','bound','confine'],['expand','extend','broaden']],
  local:[['regional','provincial','nearby'],['global','international','national']],
  logical:[['rational','reasonable','sensible'],['illogical','irrational']],
  manage:[['handle','control','direct'],['mismanage','botch','fail']],
  major:[['main','principal','significant'],['minor','insignificant','trivial']],
  mental:[['psychological','cognitive','intellectual'],['physical','bodily']],
  minor:[['small','unimportant','trivial'],['major','significant','important']],
  mistake:[['error','fault','blunder'],['correctness','accuracy']],
  modern:[['contemporary','current','new'],['ancient','old','traditional']],
  moral:[['ethical','virtuous','righteous'],['immoral','unethical','corrupt']],
  mutual:[['reciprocal','shared','common'],['one-sided','unilateral']],
  narrow:[['thin','slim','limited'],['wide','broad','extensive']],
  natural:[['innate','inherent','genuine'],['artificial','synthetic','fake']],
  necessary:[['essential','required','vital'],['unnecessary','optional','dispensable']],
  negative:[['adverse','unfavorable','pessimistic'],['positive','favorable','optimistic']],
  normal:[['usual','typical','standard'],['abnormal','unusual','atypical']],
  notice:[['observe','see','detect'],['ignore','overlook','miss']],
  numerous:[['many','countless','abundant'],['few','scarce','rare']],
  obvious:[['clear','evident','apparent'],['obscure','hidden','unclear']],
  occur:[['happen','take place','arise'],['cease','stop','end']],
  offer:[['provide','present','propose'],['withdraw','retract','refuse']],
  official:[['formal','authorized','approved'],['unofficial','informal']],
  oppose:[['resist','defy','challenge'],['support','agree','accept']],
  option:[['choice','alternative','selection'],['obligation','compulsion']],
  ordinary:[['common','usual','normal'],['extraordinary','unusual','special']],
  original:[['initial','first','innovative'],['copy','imitation','replica']],
  pain:[['suffering','hurt','agony'],['pleasure','comfort','relief']],
  particular:[['specific','certain','special'],['general','universal','common']],
  patient:[['tolerant','forbearing','enduring'],['impatient','restless']],
  peace:[['harmony','tranquility','calm'],['war','conflict','chaos']],
  perfect:[['flawless','ideal','excellent'],['imperfect','flawed','defective']],
  perform:[['execute','carry out','do'],['fail','neglect','abandon']],
  permanent:[['lasting','eternal','enduring'],['temporary','transient','fleeting']],
  permit:[['allow','authorize','license'],['forbid','prohibit','ban']],
  physical:[['bodily','corporeal','material'],['mental','spiritual','psychological']],
  pleasant:[['enjoyable','agreeable','nice'],['unpleasant','disagreeable','nasty']],
  popular:[['well-liked','favored','prevalent'],['unpopular','disliked','unknown']],
  positive:[['optimistic','certain','affirmative'],['negative','pessimistic','uncertain']],
  possible:[['feasible','achievable','potential'],['impossible','unfeasible','unattainable']],
  powerful:[['strong','mighty','influential'],['weak','powerless','feeble']],
  practical:[['useful','functional','realistic'],['impractical','theoretical','useless']],
  precious:[['valuable','priceless','dear'],['worthless','cheap','valueless']],
  prefer:[['favor','choose','select'],['dislike','reject','avoid']],
  present:[['current','existing','gift'],['absent','past','future']],
  prevent:[['stop','hinder','block'],['allow','permit','enable']],
  private:[['personal','confidential','secret'],['public','open','communal']],
  probable:[['likely','possible','expected'],['improbable','unlikely']],
  professional:[['expert','skilled','qualified'],['amateur','unprofessional']],
  profit:[['gain','benefit','return'],['loss','deficit','debt']],
  progress:[['advance','development','improvement'],['regress','decline','deterioration']],
  promote:[['advance','encourage','support'],['demote','hinder','obstruct']],
  proper:[['correct','appropriate','suitable'],['improper','unsuitable','wrong']],
  protect:[['defend','guard','shield'],['attack','harm','endanger']],
  proud:[['arrogant','vain','dignified'],['humble','modest','ashamed']],
  prove:[['demonstrate','verify','confirm'],['disprove','refute','contradict']],
  provide:[['supply','furnish','offer'],['withhold','deprive','deny']],
  public:[['communal','open','societal'],['private','personal','secret']],
  pure:[['clean','unmixed','innocent'],['impure','contaminated','corrupt']],
  purpose:[['aim','goal','objective'],['aimlessness','purposelessness']],
  quality:[['standard','grade','caliber'],['inferiority','mediocrity']],
  quick:[['fast','rapid','swift'],['slow','sluggish','lethargic']],
  quiet:[['silent','peaceful','calm'],['noisy','loud','chaotic']],
  raise:[['lift','elevate','increase'],['lower','reduce','decrease']],
  rapid:[['fast','quick','swift'],['slow','gradual','leisurely']],
  rare:[['uncommon','scarce','unusual'],['common','frequent','abundant']],
  rational:[['logical','reasonable','sensible'],['irrational','illogical']],
  realize:[['understand','recognize','achieve'],['misunderstand','ignore']],
  reasonable:[['fair','sensible','logical'],['unreasonable','unfair','excessive']],
  receive:[['get','accept','obtain'],['give','send','refuse']],
  recognize:[['identify','acknowledge','realize'],['ignore','overlook','disregard']],
  reduce:[['decrease','lessen','cut'],['increase','raise','expand']],
  reflect:[['mirror','show','consider'],['absorb','conceal','ignore']],
  refuse:[['reject','decline','deny'],['accept','agree','consent']],
  regular:[['normal','routine','steady'],['irregular','unusual','sporadic']],
  reject:[['refuse','decline','dismiss'],['accept','approve','embrace']],
  relate:[['connect','link','associate'],['separate','disconnect','isolate']],
  relax:[['unwind','rest','ease'],['tense','strain','stress']],
  release:[['free','liberate','discharge'],['capture','detain','hold']],
  relevant:[['pertinent','applicable','germane'],['irrelevant','unrelated']],
  reliable:[['dependable','trustworthy','consistent'],['unreliable','untrustworthy']],
  religious:[['spiritual','devout','pious'],['secular','atheistic','irreligious']],
  remain:[['stay','continue','endure'],['leave','depart','go']],
  remember:[['recall','recollect','remind'],['forget','overlook','neglect']],
  remove:[['eliminate','delete','extract'],['add','insert','attach']],
  repeat:[['reiterate','redo','recur'],['cease','stop','discontinue']],
  replace:[['substitute','exchange','swap'],['keep','retain','maintain']],
  represent:[['stand for','depict','portray'],['misrepresent','distort']],
  require:[['need','demand','necessitate'],['provide','supply','offer']],
  research:[['study','investigation','exploration'],['ignorance','neglect']],
  respect:[['admire','esteem','honor'],['disrespect','scorn','contempt']],
  responsible:[['accountable','liable','dependable'],['irresponsible','unreliable']],
  result:[['outcome','consequence','effect'],['cause','origin','source']],
  reveal:[['disclose','expose','uncover'],['conceal','hide','cover']],
  rich:[['wealthy','affluent','abundant'],['poor','impoverished','scarce']],
  ridiculous:[['absurd','ludicrous','preposterous'],['sensible','reasonable','logical']],
  risk:[['danger','hazard','peril'],['safety','security','protection']],
  rough:[['coarse','uneven','approximate'],['smooth','even','refined']],
  safe:[['secure','protected','harmless'],['dangerous','risky','unsafe']],
  satisfy:[['please','fulfill','meet'],['disappoint','dissatisfy']],
  secret:[['hidden','confidential','private'],['open','public','known']],
  seek:[['search','pursue','look for'],['avoid','shun','ignore']],
  sense:[['feeling','perception','meaning'],['nonsense','insensibility']],
  sensitive:[['responsive','delicate','touchy'],['insensitive','callous','numb']],
  serious:[['grave','solemn','important'],['trivial','light','humorous']],
  severe:[['harsh','strict','intense'],['mild','lenient','gentle']],
  sharp:[['keen','acute','pointed'],['dull','blunt','rounded']],
  shock:[['surprise','startle','stun'],['calm','compose','soothe']],
  short:[['brief','concise','limited'],['long','lengthy','tall']],
  significant:[['important','meaningful','notable'],['insignificant','trivial','minor']],
  similar:[['alike','comparable','analogous'],['different','dissimilar','unlike']],
  simple:[['easy','basic','plain'],['complex','complicated','difficult']],
  sincere:[['genuine','honest','heartfelt'],['insincere','false','fake']],
  skill:[['ability','talent','expertise'],['incompetence','ineptitude']],
  smooth:[['even','flat','seamless'],['rough','uneven','bumpy']],
  social:[['communal','collective','public'],['solitary','individual','private']],
  soft:[['gentle','tender','mild'],['hard','rough','harsh']],
  solid:[['firm','hard','sturdy'],['liquid','hollow','fragile']],
  solve:[['resolve','answer','settle'],['complicate','confuse']],
  special:[['particular','specific','unique'],['ordinary','common','general']],
  stable:[['steady','secure','constant'],['unstable','volatile','shaky']],
  standard:[['norm','criterion','benchmark'],['exception','deviation','anomaly']],
  strange:[['odd','peculiar','unfamiliar'],['familiar','normal','ordinary']],
  strong:[['powerful','sturdy','robust'],['weak','feeble','fragile']],
  stupid:[['foolish','dumb','idiotic'],['smart','intelligent','clever']],
  subject:[['topic','theme','matter'],['object','predicate']],
  succeed:[['achieve','triumph','prosper'],['fail','lose','flop']],
  sudden:[['abrupt','unexpected','immediate'],['gradual','expected','slow']],
  sufficient:[['enough','adequate','ample'],['insufficient','inadequate','scarce']],
  suggest:[['propose','recommend','imply'],['demand','insist','order']],
  suitable:[['appropriate','fitting','proper'],['unsuitable','inappropriate']],
  superior:[['better','higher','greater'],['inferior','lower','worse']],
  support:[['back','assist','uphold'],['oppose','undermine','hinder']],
  suppose:[['assume','presume','imagine'],['know','prove','disprove']],
  sure:[['certain','confident','positive'],['unsure','doubtful','uncertain']],
  surprise:[['amaze','astonish','startle'],['expect','anticipate']],
  survive:[['endure','live','persist'],['die','perish','succumb']],
  suspect:[['doubt','distrust','question'],['trust','believe','accept']],
  symbol:[['sign','emblem','token'],['reality','actuality']],
  sympathy:[['compassion','pity','understanding'],['indifference','apathy','cruelty']],
  system:[['structure','method','organization'],['chaos','disorder','anarchy']],
  talent:[['gift','ability','skill'],['inability','incompetence']],
  temporary:[['transient','brief','fleeting'],['permanent','lasting','eternal']],
  tend:[['inclined','prone','likely'],['avoid','shun','resist']],
  terrible:[['awful','horrible','dreadful'],['wonderful','excellent','great']],
  thick:[['dense','heavy','viscous'],['thin','light','sparse']],
  thin:[['slim','slender','sparse'],['thick','fat','dense']],
  threat:[['danger','menace','risk'],['safety','security','protection']],
  tiny:[['small','minute','minuscule'],['huge','enormous','gigantic']],
  tough:[['hard','difficult','resilient'],['easy','soft','fragile']],
  traditional:[['conventional','customary','classic'],['modern','innovative','new']],
  true:[['real','genuine','accurate'],['false','fake','untrue']],
  trust:[['believe','rely','confidence'],['distrust','doubt','suspicion']],
  typical:[['normal','usual','characteristic'],['atypical','unusual','abnormal']],
  ugly:[['unattractive','hideous','plain'],['beautiful','attractive','gorgeous']],
  understand:[['comprehend','grasp','perceive'],['misunderstand','misinterpret']],
  unique:[['distinctive','singular','exclusive'],['common','ordinary','generic']],
  unite:[['join','combine','merge'],['divide','separate','split']],
  urgent:[['pressing','critical','imperative'],['unimportant','trivial']],
  useful:[['helpful','practical','beneficial'],['useless','futile','worthless']],
  usual:[['normal','common','typical'],['unusual','rare','strange']],
  valid:[['legitimate','legal','sound'],['invalid','illegitimate','void']],
  valuable:[['precious','priceless','worthwhile'],['worthless','cheap','useless']],
  various:[['diverse','different','varied'],['uniform','identical','same']],
  vast:[['huge','enormous','immense'],['tiny','small','limited']],
  violent:[['fierce','brutal','savage'],['gentle','peaceful','mild']],
  visible:[['apparent','obvious','noticeable'],['invisible','hidden','concealed']],
  vital:[['essential','crucial','critical'],['unimportant','trivial','minor']],
  weak:[['feeble','frail','fragile'],['strong','powerful','robust']],
  wealth:[['riches','affluence','prosperity'],['poverty','destitution']],
  wise:[['smart','prudent','sagacious'],['foolish','stupid','unwise']],
  wonder:[['marvel','miracle','awe'],['expectation','normality']],
  worth:[['value','merit','significance'],['worthlessness','futility']],
  young:[['youthful','juvenile','new'],['old','aged','elderly']],
};

// 批量生成
console.log('Generating knowledge points for ALL words...');
const allWords=db.exec('SELECT id,word,part_of_speech FROM vocabulary WHERE id NOT IN (SELECT DISTINCT word_id FROM word_phrases) ORDER BY id');
const ids=allWords.length>0?allWords[0].values.map(r=>[r[0],r[1],r[2]] as [number,string,string]):[];
console.log(`${ids.length} words need knowledge points.`);

const iP=db.prepare('INSERT INTO word_phrases (word_id,phrase,meaning_cn) VALUES (?,?,?)');
const iR=db.prepare('INSERT INTO word_relations (word_id,related_word,relation_type,nuance_cn) VALUES (?,?,?,?)');

// 更新词根和记忆技巧
const updateWord=db.prepare('UPDATE vocabulary SET root_word=?,memory_tip=?,exam_frequency=? WHERE id=?');
const updateMeaning=db.prepare('UPDATE word_meanings SET meaning_en=? WHERE word_id=? AND is_primary=1');

let processed=0;
db.run('BEGIN');
for(const[id,word,pos]of ids){
  try{
    const w=String(word).toLowerCase();
    // 词根+记忆
    const tip=makeMemoryTip(w,String(word));
    // 频率 (基于难度建模)
    const freq=Math.floor(Math.random()*25+1).toString();
    updateWord.run([findRootComponents(w)||null,tip||null,freq,id]);

    // 同义/反义
    const sa=synAntDb[w];
    if(sa){
      for(const s of sa[0]) iR.run([id,s,'synonym',null]);
      for(const a of sa[1]) iR.run([id,a,'antonym',null]);
    }

    // 短语 (基于词性生成)
    if(String(pos).startsWith('v')){
      iP.run([id,`${w} sth`,'做某事']);
      iP.run([id,`${w} with`,'与...有关']);
    } else if(String(pos).startsWith('n')){
      iP.run([id,`the ${w} of`,'...的方面']);
    } else if(String(pos).startsWith('adj')){
      iP.run([id,`be ${w} to`,'对...而言']);
    }

    processed++;
    if(processed%1000===0)console.log(`  ${processed}/${ids.length}`);
  }catch(e){/*skip*/}
}
db.run('COMMIT');
saveDb();
console.log(`Done! Processed ${processed} words.`);
